### ISSUE TITLE
asMapValue() and asArrayValue add extra quotes to keys and string values

### ISSUE THREAD

**Issue by dperetti** [msgpack/msgpack-java#110]
Android, msgpack-java 0.6.11 : asMapValue() and asArrayValue() add extra quotes to keys and string values.

It looks like the issue boils down to this :

    ValueFactory.createRawValue("1234").toString().length()

Result : 6 ! (because of the extra quotes).

**Comment by komamitsu** [comment]
Sorry for too late reply. That seems the specification of `org.msgpack.type.AbstractRawValue#toString()`. Not a bug.

**Comment by komamitsu** [comment]
I'm closing this issue. Please re-open it if you still have any problem.
