### ISSUE TITLE
Is org.msgpack.MessagePack thread safe?

### ISSUE THREAD

**Issue by JensRantil** [msgpack/msgpack-java#122]
Just curious.

**Comment by xerial** [comment]
MessagePack reader and writers are designed for single-thread use. If you need to make them thread-safe, you need to wrap every call to packXXX/unpackXXX with some synchronization block. 

But I recommend you to let each thread use separate MessagePacker/Unpacker, then concatenate the results. It should be much faster than accessing single packer/unpacker instances concurrently.
