### ISSUE TITLE
Why is org.msgpack.MessageTypeException an RuntimeException?

### ISSUE THREAD

**Issue by lukasz-fracz** [msgpack/msgpack-java#132]
Hi
I am using MessagePack in my application, and today it crashed for no reason. As I started to investige what's going on, I quickly realized it was an  uncaught exception - MessageTypeException. So, my question is: why is it an RuntimeException?

**Comment by komamitsu** [comment]
Sorry for my late reply. Did you check the status code of the HTTP response? In that case, your HTTP client can detect HTTP server is unavailable with checking the status code and it should handle the error without unpacking the response.

**Comment by lukasz-fracz** [comment]
No, I did not. 
You're right, that should handle it.
