### ISSUE TITLE
HI,V0.7 is too slower than V0.6,Why?Why?

### ISSUE THREAD

**Issue by GutasCo** [msgpack/msgpack-java#162]
hi,I just did a simple testing
for (int i = 0; i < 50*10000; i++) {
                         ByteArrayOutputStream out = new ByteArrayOutputStream();
			MessagePacker packer = MessagePack.newDefaultPacker(out);
			packer.packInt(1000);
			packer.packFloat(1000);
			packer.packByte((byte) 10);
			packer.packDouble(1000);
			packer.packInt(1000);
			packer.packFloat(1000);
			packer.packByte((byte) 10);
			packer.packDouble(1000);
			packer.packShort((short) 12);
			packer.packString("123769780");
}
It take 2040 milliseconds, msgpack V0.7 x86 jdk1.8

for (int i = 0; i < 50*10000; i++) {
			ByteArrayOutputStream out = new ByteArrayOutputStream();
			Packer packer =msgpack.createPacker (out);
			packer.write(1000);
			packer.write(1000);
			packer.write((byte) 10);
			packer.write(1000);
			packer.write(1000);
			packer.write(1000);
			packer.write((byte) 10);
			packer.write(1000);
			packer.write((short) 12);
			packer.write("123769780");	
		}
It take only 642 milliseconds, msgpack V0.6  x86 jdk1.8

then I read some codes and assume the method "ensureCapacity()" in MessagePacker.java v0.7 waste of many times, the buff always null at first time and need to flush() and  out.next(....)

**Comment by xerial** [comment]
Thanks! Now close this ticket.
