### ISSUE TITLE
StringValueImpl and RawStringValueImpl does not satisfy equals/hashCode laws

### ISSUE THREAD

**Issue by xuwei-k** [msgpack/msgpack-java#164]
version 0.7.0-p2

```scala
val str = "a"
val a1 = ValueFactory.newRawString(str.getBytes("UTF-8"))
val a2 = ValueFactory.newString(str)
println(a1 == a2) // true
println(a1.hashCode) // 128
println(a2.hashCode) // 97
```

`a1.hashCode` should be same as `a2.hashCode` if `a1.equals(a2)`

**Comment by komamitsu** [comment]
@xuwei-k Thanks for reporting!

@xerial I added some changes to fix this issue on https://github.com/msgpack/msgpack-java/pull/168. Can you review this PR when you have time?
