### ISSUE TITLE
Unable to unpack data using JSON() when packed by other message pack

### ISSUE THREAD

**Issue by FransBosuil** [msgpack/msgpack-java#167]
Using version 0.6.11, it is not possible to unpack data (packed by e.g. MessagePack) using the JSON message pack. Would it be possible to indicate how this issue can be resolved?

As MessagePack is like JSON, I would expect that all msgpack'ed data would be unpackable by the JSON unpacker. Would it be possible to indicate if my assumption is correct?

Possible related issue https://github.com/msgpack/msgpack-java/issues/61

### Test code    
    public static void main(String[] args) throws IOException {
        System.out.println("Create test data");
        BufferPacker packer = new MessagePack().createBufferPacker();
        packer.write(1);
        packer.write(2);
        byte[] bytes = packer.toByteArray();

        System.out.println("Unpack using new MessagePack()");
        unpack(bytes, new MessagePack());

        System.out.println("Unpack using new JSON()");
        unpack(bytes, new JSON());
    }

    private static void unpack(byte[] bytes, MessagePack msgpack) throws IOException {
        Unpacker unpacker = msgpack.createBufferUnpacker(bytes);
        System.out.println(unpacker.readInt());
        System.out.println(unpacker.readInt());
    }

### Output
    
    Create test data
    Unpack using new MessagePack()
    1
    2
    Unpack using new JSON()
    Exception in thread "main" java.io.IOException: Unexpected character () at position 0.
    	at org.msgpack.util.json.JSONUnpacker.nextValue(JSONUnpacker.java:58)
    	at org.msgpack.unpacker.Converter.ensureValue(Converter.java:54)
    	at org.msgpack.unpacker.Converter.getTop(Converter.java:274)
    	at org.msgpack.unpacker.Converter.readInt(Converter.java:130)
    	at test.JSONTest.unpack(JSONTest.java:28)
    	at test.JSONTest.main(JSONTest.java:23)
    Caused by: Unexpected character () at position 0.
    	at org.json.simple.parser.Yylex.yylex(Yylex.java:610)
    	at org.json.simple.parser.JSONParser.nextToken(JSONParser.java:269)
    	at org.json.simple.parser.JSONParser.parse(JSONParser.java:118)
    	at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
    	at org.msgpack.util.json.JSONUnpacker.nextValue(JSONUnpacker.java:55)
    	... 5 more

**Comment by FransBosuil** [comment]
Hi @komamitsu, thank you for the swift response. Updating to v0.7 is planned for the near future.But, I guess, it will not solve my issue.

Related to the issue, when using a Javascript implementation, the MessagePack'ed data is unpacked in a valid Javascript object, which (if I'm not mistaken) is like a JSON object. So, I assumed the JSON unpacker would do the same. The example below reflects more the mentioned issue as it packs a valid JSON structure (http://msgpack.org/).

Note that,
 - the JSON unpacker should not return the same Java object as the MessagePack unpacker. It should return a JSON object representing the MessagePack'ed data. 
 - in some cases (like the example above), the MessagePack'ed data cannot be unpacked as a valid JSON structure. In these cases, it is acceptable to give an error.

### Test code    
    public static void main(String[] args) throws IOException {
        System.out.println("Create test data");
        BufferPacker packer = new MessagePack().createBufferPacker();
        packer.writeMapBegin(2);
        packer.write("compact");
        packer.write(true);
        packer.write("schema");
        packer.write(0);
        packer.writeMapEnd();
        byte[] bytes = packer.toByteArray();

        System.out.println("Unpack using new MessagePack()");
        unpack(bytes, new MessagePack());

        System.out.println("Unpack using new JSON()");
        unpack(bytes, new JSON());
    }

    private static void unpack(byte[] bytes, MessagePack msgpack) throws IOException {
        Unpacker unpacker = msgpack.createBufferUnpacker(bytes);
        unpacker.readMapBegin();
        System.out.println("  " + unpacker.readString() + " " + unpacker.readBoolean());
        System.out.println("  " + unpacker.readString() + " " + unpacker.readInt());
        unpacker.readMapEnd();
    }

**Comment by komamitsu** [comment]
@FransBosuil Actually, users can use MessagePack like JSON in term of schema less, but the serialized data are completely different. JSON is a text format, while MessagePack is a binary format. So MessagePacked data can't be unpacked in JSON. The opposite is true.

```
    unpack(bytes, new JSON());
```
^ This `bytes` is packed in MessagePack format, so you can't unpack it with org.msgpack.JSON.

**Comment by FransBosuil** [comment]
Hi @komamitsu, thank you for the swift response. I think I'm starting to understand the issue. Please correct me if I'm wrong.

- The JSON class packs a java object in a text string and unpacks a text string in a java object.
- The MessagePack class packs a java object into a byte array and unpacks the byte array in a java object.

My (wrong) assumption was that the JSON class packed a JSON java object into a msgpack-ed byte array and unpacked a msgpack-ed byte array in a JSON java object. Hence making it possible to unpack other msgpack-ed byte arrays in a JSON java object.

So, to resolve my issue, I would need to write my own MessagePack extension that writes JSON java objects into a byte array and that reads JSON java objects from a byte array. E.g. by using jackson-json. Is this correct?

**Comment by komamitsu** [comment]
@FransBosuil Your understanding on the difference of them is correct. 

Let me clarify some points.

> that writes JSON java objects
- You mean `org.msgpack.util.json.JSON` by `JSON java objects'?
- What's your actual trouble? You just need to convert a JSON format string to MessagePack byte array, or the reverse?

**Comment by FransBosuil** [comment]
- No, more something like 'http://www.json.org/javadoc/org/json/JSONObject.html'.
- I have a complex model structure. I have a JSON and MsgPack encoder which encode the model into a JSON and a MsgPack file. Now, I want to be sure that both files contain the same data. So, I was trying to decode both files as JSON objects which I could compare. I thought the JSON message pack would help me with this.

**Comment by komamitsu** [comment]
You can unpack JSON and MessagePack format files and compare those unpacked Java objects like this:
```

    @Message
    static class Person {
        public String name;
        public int age;

        @Override
        public String toString() {
            return "Person{" +
                    "name='" + name + '\'' +
                    ", age=" + age +
                    '}';
        }
    }


            :
        Person origPerson = new Person();
        origPerson.name = "foobar";
        origPerson.age = 42;

        // Prepare packed data instead of JSON and MessagePack files
        MessagePack messagePack = new MessagePack();
        ByteArrayOutputStream outMsgpack = new ByteArrayOutputStream();
        messagePack.createPacker(outMsgpack).write(origPerson);

        JSON json = new JSON();
        ByteArrayOutputStream outJson = new ByteArrayOutputStream();
        json.createPacker(outJson).write(origPerson);

        // Use ByteArrayInputStream instead of FileInputStream for simplicity
        Person fromMsgpack = messagePack.createUnpacker(new ByteArrayInputStream(outMsgpack.toByteArray())).read(Person.class);
        System.out.println(fromMsgpack);        // >> Person{name='foobar', age=42}

        Person fromJson = json.createUnpacker(new ByteArrayInputStream(outJson.toByteArray())).read(Person.class);
        System.out.println(fromJson);        // >> Person{name='foobar', age=42}
```

**Comment by FransBosuil** [comment]
Indeed, this is already one of the tests. But, depending on the registered packers, it could be that the two files are still not consistent. This would be an issue if one would use the data in e.g. JavaScript. The json.parse and msgpack.unpack results should be similar. 

Now, for example, the keys are not stored in my msgpack format, the values are stored in an array. This means that the javascript unpackers should have a dictionary or something to map the unpacked values to the correct keys. Note that both file set will be decoded to the same model on the Java side!

To resolve this, I would need to extend the packers to also decode the keys. And, to test, if I have not forgotten something, I would like to decode both files into a JavaScript like object (JSON) and compare them. This way, I can easily switch between the formats without having to update the JavaScript code.

**Comment by FransBosuil** [comment]
@komamitsu Thank you for the support. MessagePack v0.7 allows me to implement the required test. An example...
    
        // Create the msgpack-ed data
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        MessagePacker packer = MessagePack.newDefaultPacker(os);
        packer.packMapHeader(2);
        packer.packString("compact");
        packer.packBoolean(true);
        packer.packString("schema");
        packer.packInt(0);
        packer.flush();
        byte[] bytes = os.toByteArray();

        // Convert the msgpack-ed data to a JSON string
        StringWriter string_writer = new StringWriter();
        try {
            ObjectMapper objectWriter = new ObjectMapper(new JsonFactory());
    	    ObjectMapper objectReader = new ObjectMapper(new MessagePackFactory());
    		
    	    TypeReference<TreeMap<String, Object>> typeReference = new TypeReference<TreeMap<String, Object>>() {};
    	    objectWriter.writeValue(string_writer, objectReader.readValue(bytes, typeReference));
        }
        finally {
            string_writer.flush();			
    	    string_writer.close();
        }

        // Check if the correct JSON string is generated
        Assert.assertEquals("{\"compact\":true,\"schema\":0}", string_writer.toString());

**Comment by komamitsu** [comment]
@FransBosuil I'm closing this issue. Please reopen it if you still have a problem.
