### ISSUE TITLE
Reconsider calling close() of the previous assigned stream or channel in MessageBuffer(Input|Output)#reset

### ISSUE THREAD

**Issue by komamitsu** [msgpack/msgpack-java#173]
In https://github.com/msgpack/msgpack-java/pull/169 and https://github.com/msgpack/msgpack-java/pull/170, we made some changes to call a previously assigned stream or channel instead of a new one passed as a parameter.

But I found https://github.com/spring-projects/spring-framework does the followings when it returns a HTTP request with jackson-dataformat-msgpack.
- Reuses an OutputStream (`org.apache.catalina.connector.CoyoteOutputStream`) without having called its close()
 - Of course, it includes a new `SocketChannel` each time
- Creates a new `org.msgpack.jackson.dataformat.MessagePackGenerator`
 - Which calls `org.msgpack.core.buffer.OutputStreamBufferOutput#reset` internally except for the first time 

As a result, the OutputStream the framework tries to reuse will be closed unexpectedly and MessagePack fails to write data to it.

Also, on second thought, I think MessageBuffer(Input|Output)#reset shouldn't close the previous output or channel for the following reasons.
- Closing the previous output or channel in the methods is unexpected behaviour for the user and we can't know what it causes (it depends on their implementation)
- Releasing those resources are basically the user's responsibility

Also, on second thought, it sounds MessageBuffer(Input|Output)#reset shouldn't close the previous output or channel for the following reasons.

@xerial What do you think? If the above ideas sound good, I can fix this issue easily.

**Comment by xerial** [comment]
OK. Delegate the responsibility of closing the previous stream and channel to the caller of `reset` methods. I think changing the return value of `reset` to OutputStream (or OutputChannel) and never closing it inside `reset` method are sufficient.

**Comment by komamitsu** [comment]
`MessagePacker` and `MessageUnpacker` have `reset()` method too that calls `MessageBuffer(Input|Output)#reset` internally. If we decide to make `MessageBuffer(Input|Output)#reset` return the previously assigned `(Input|Output)` Stream or Channel, `Message(Packer|Unpacker)#reset` should return it as well. But it needs more implementation. So I just removed the closing of the old `(Input|Output)` Stream or Channel in https://github.com/msgpack/msgpack-java/pull/175 for now.

Also, the integration of https://github.com/spring-projects/spring-framework and jackson-dataformat-msgpack work well with the PR.
https://github.com/komamitsu/SpringBootExample

**Comment by komamitsu** [comment]
Ah, I had a wrong idea. This is false. > MessagePacker and MessageUnpacker have reset() method too that calls MessageBuffer(Input|Output)#reset internally

I made reset() return the old resource and pushed it again.

**Comment by xerial** [comment]
gj! thanks.
