### ISSUE TITLE
java.lang.UnsupportedOperationException in MessagePackParser#getTokenLocation is confusing

### ISSUE THREAD

**Issue by making** [msgpack/msgpack-java#178]
I'm using jackson-data-bind 2.4.4 and jackson-dataformat-msgpack 0.7.0-p3

`UnsupportedOperationException` is thrown when no suitable constructor is found in deserializing an object.

in `com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1071)`

``` java
        throw JsonMappingException.from(jp, "No suitable constructor found for type "
                +_beanType+": can not instantiate from JSON object (need to add/enable type information?)");
```
`JsonMappingException#from` is called 
and in `com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)`

``` java
    public static JsonMappingException from(JsonParser jp, String msg) {
        return new JsonMappingException(msg, ((jp == null) ? null : jp.getTokenLocation()));
    }
```

`JsonParser#getTokenLocation` is called.

in `org.msgpack.jackson.dataformat.MessagePackParser.getTokenLocation(MessagePackParser.java:305)` 

``` java
    @Override
    public JsonLocation getTokenLocation() {
        throw new UnsupportedOperationException("Not implemented yet");
    }
```

Not implemented yet :frowning:

Since the original exception is disappeared, users could be confused what is happened.
In my case, it took time i realized the original reason was that the constructor was invalid.

**Comment by komamitsu** [comment]
@making Thanks for reporting! Let me check it.

**Comment by komamitsu** [comment]
This issue was fixed in https://github.com/msgpack/msgpack-java/pull/182.
