### ISSUE TITLE
Suggest to add packer/unpacker methods like packerByteArray/unpackByteArray

### ISSUE THREAD

**Issue by axeon** [msgpack/msgpack-java#184]
Suggest to add packer/unpacker methods like packerByteArray/unpackByteArray.
When i pack byte[] data, must be use packArrayHeader and a loop invoke packByte.
If add packerByteArray method, the msgpack-java will use System.arrayCopy to improve performance.

thank you!

**Comment by xerial** [comment]
Use packBinary(len) and writePayload instead:
https://github.com/msgpack/msgpack-java/blob/v07-develop/msgpack-core/src/main/java/org/msgpack/core/example/MessagePackExample.java#L123-L126
