### ISSUE TITLE
Automatic class register

### ISSUE THREAD

**Issue by ghetolay** [msgpack/msgpack-java#19]
It's not really a issue it's a question : 

Why can't classes be automatically registered ?

I'm actually working with JSON and I need something similar for binary data. Message Pack looks really great but the registration is a big problem for me. I'm working in a API so I don't know which classes will need to be registered. 
Why TemplateRegistry does not register the class if he do not find a matching template ?

**Comment by komamitsu** [comment]
> I search about solution and it's seems that the only solution is the one used by JackSon with the TypeReference class

@ghetolay Very sorry for late reply. We added https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson that can be used via jackson-databind and it would resolve this kind of issue.

**Comment by ghetolay** [comment]
Well I'm not working on my [library](https://github.com/ghetolay/jwamp) anymore but I'll probably work with msgpack on something else so I'll look into it. Thks.
