### ISSUE TITLE
Supporting platform that has no sun.misc.Unsafe

### ISSUE THREAD

**Issue by xerial** [msgpack/msgpack-java#194]
We have got an report that the current msgpack-core doesn't work in GAE. MessageBuffer implementation is designed to achieve the best performance for accessing memory through sun.misc.Unsafe. But Unsafe is not avilable in GAE.

 - Loading sun.misc.Unsafe might fail in GAE. 
  - Simply referencing it in the code (in import statement or field declaration) may have no problem; @xuwei-k reported the error log when using msgpack-core-0.7.0-p5 in https://gist.github.com/xuwei-k/31f9c9256439af0c3272  (error occurred after `Unsafe u;` statement)
  - Android has sun.misc.Unsafe so there was a workaround #180
 - We NEVER create any interface for MessageBuffer because it changes invokevirtual calls to invokeinterface and deteriorates the performance. And also having two or more classes that implement MessageBuffer methods generates TypeProfile. It makes each method call 2x slower.

**Comment by xerial** [comment]
I'm working on this task on https://github.com/xerial/msgpack-java/tree/v07-no-unsafe branch. 

I have succeeded in using MessageBufferU, which does not rely on Unsafe class. Another problem is there is no java.nio.DirectByteBufffer in GAE. I'm seeking a workaround.

**Comment by xerial** [comment]
Just deployed 0.7.0-p7, which supports GAE.

**Comment by oza** [comment]
Good job!
