### ISSUE TITLE
str8 with length > 127 leads to Bad limit exception, v0.6.11

### ISSUE THREAD

**Issue by ArcsinX** [msgpack/msgpack-java#213]
Problem is in the following code of MessagePackUnpacker.java
```
...
       case 0xd9: // str 8
        {
              int count = in.getByte();
...
```
byte is a signed type!
If string length > 127, then count will be negative number, so tryReferRawBody will be called with second parameter as negative number. 
```
...
            if (!tryReferRawBody(a, count)) {

...
```
Thus we will get java.lang.IllegalArgumentException: Bad limit (capacity 1024): -65 expection

**Comment by komamitsu** [comment]
@ArcsinX Sorry for our late reply. This bug was fixed in https://github.com/msgpack/msgpack-java/pull/130. I released 0.6.12 in the last hour that includes the fix. Thanks.
