### ISSUE TITLE
Different serialized results in different devices(Nexus 5 , Moto X)

### ISSUE THREAD

**Issue by ChaosLeong** [msgpack/msgpack-java#214]
I test the serialization in my Nexus 5 and Moto X. However,I found it have different results.
Is it a bug ?

不同设备序列化结果不一样（测试设备：Nexus5、MotoX）

**Comment by komamitsu** [comment]
@ChaosLeong Can you some examples of this issue?

**Comment by ChaosLeong** [comment]
Envelope.java
```java
@Message
public class Envelope{
    public int version=-1;
}
```
Example code:
```java
MessagePack messagePack = new MessagePack();
Envelope envelope = new Envelope();
envelope.version = 1;
byte[] bytes = messagePack.write(envelope);
```

bytes in Moto X:
![image](https://cloud.githubusercontent.com/assets/6824996/7083341/15ac27ea-df93-11e4-873c-e1e3c992f90b.png)


bytes in Nexus 5:
![image](https://cloud.githubusercontent.com/assets/6824996/7083330/ed42e92e-df92-11e4-944a-579c0a70b35d.png)

**Comment by RoSkin** [comment]
How can I pack jAVA Object in V7?

**Comment by komamitsu** [comment]
@ChaosLeong I got `[-111, 1]` with the example code not `[-36, 0, 16, ...]`. Did you really get the serialized data with it?

**Comment by komamitsu** [comment]
@RoSkin Please see https://github.com/msgpack/msgpack-java/blob/v07-develop/msgpack-core/src/main/java/org/msgpack/core/example/MessagePackExample.java and https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson.

**Comment by ChaosLeong** [comment]
@komamitsu The complete Envelope.java as follows.

    @org.msgpack.annotation.Message
    public class Envelope {

        /**
         * required Field
         */
        public int version = -1;

        /**
         * optional Field
         */
        @Optional public long timeMillis;
        @Optional public long upTimeMillis;
        @Optional public String timezone;
        @Optional public Message message;
        @Optional public Request request;
        @Optional public Info info;
        @Optional public DeviceInfo deviceInfo;
        @Optional public FeatureInfo featureInfo;
        @Optional public boolean wifiInfoRequest;
        @Optional public SetupRequest setupRequest;
        @Optional public InfoRequest infoRequest;
        @Optional public InfoResponse infoResponse;
        @Optional public SendRequest sendRequest;
        @Optional public List<Entity> entities;
        @Optional public List<Notification> notifications;

        /**
         * Message
         */

        @org.msgpack.annotation.Message
        public static final class InfoRequest {
        }

        @org.msgpack.annotation.Message
        public static final class InfoResponse {
        }

        @org.msgpack.annotation.Message
        public static final class SetupRequest {
        }

        @org.msgpack.annotation.Message
        public static final class Info {
        }

        @org.msgpack.annotation.Message
        public static final class DeviceInfo {
        }

        @org.msgpack.annotation.Message
        public static final class FeatureInfo {
        }

        @org.msgpack.annotation.Message
        public static final class Notification {
        }

        @org.msgpack.annotation.Message
        public static final class SendRequest {
        }

        @org.msgpack.annotation.Message
        public static final class Entity {
        }

        @org.msgpack.annotation.Message
        public static final class Request {
        }

        @org.msgpack.annotation.Message
        public static final class Message {
        }
    }

**Comment by komamitsu** [comment]
@ChaosLeong Thanks for the information. It seems it's related to the naive implementation of https://github.com/msgpack/msgpack-java/blob/master/src/main/java/org/msgpack/template/builder/AbstractTemplateBuilder.java.

An option is to explicitly add `@Index` annotation like this:
```
        @Index(value=0)
        public int version = -1;

        @Index(value=1)
        @Optional public long timeMillis;

        @Index(value=2)
        @Optional public long upTimeMillis;
          :
```

Also, you can resolve this sort of issues using https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson if you can use msgpack-0.7.x.

```
        Envelope envelope = new Envelope();
        bytes = mapper.writeValueAsBytes(envelope);
            :
        Envelope restoredEnvelop = mapper.readValue(bytes, Envelope.class);
```

**Comment by ChaosLeong** [comment]
@komamitsu It worked, thank you.
