### ISSUE TITLE
Decoding json

### ISSUE THREAD

**Issue by behrad** [msgpack/msgpack-java#227]
I'm using msgpack javascript client to pack a json object:
```js
val json = {
  uuid: 123,
  content: 'hello'
};
```

looking issues I couldn't find a proper way to unpack them with msgpack-java (version 0.6.11 from maven) into a Java POJO...
this works

```java
MessagePack msgpack = new MessagePack();
Value dynamic = msgpack.read(msgpackPayload);
```

but working with `dynamic.asMapValue()` is not easy... I want that to be populated in my Message class:

```java
public class Message {
   public long uuid;
   public String content;
}
```

**Comment by komamitsu** [comment]
Can you try msgpack-v07? You can easily unpack the deserialized data into POJO with it like this:
```
        ObjectMapper mapper = new ObjectMapper(new MessagePackFactory());
        Message message = mapper.readValue(msgpackPayload, Message.class);
```
