### ISSUE TITLE
Generic object serialization with MsgPack and ObjectMapper

### ISSUE THREAD

**Issue by Anand-J-Kadhi** [msgpack/msgpack-java#228]
Hi,

I have a requirement that i have to serialize the object on runtime i.e any type of object can come. I am using msgpack integrated with Axon framework. So on the axon event handler i get object's on runtime which can be of any type. The serialization is done properly but the issue arises when i deserialize the byte Stream.
ex: 
```@Override
public <S, T> T deserialize(SerializedObject<S> serializedObject) {
	byte[] serializedBytes= (byte[]) serializedObject.getData();
	Object bytes = null;
	try {
		bytes=objectMapper.readValue(serializedBytes,Object.class);
		System.out.println("After deserialization : "+bytes);
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
	return (T) bytes;
}
```
where ```serializedObject``` has custom method getData() which contains the serialized bytes.
when is read the value & give representation as Object.class I get a ```LinkedHashMap``` in return value for target.
Is there any standard way to perform GENERIC serialization / deserialization for any object type.

Note : I don't want to save the information for the object type (class) in database.

**Comment by komamitsu** [comment]
Unfortunately, I don't think it's possible to deserialize any object without type information.

**Comment by Anand-J-Kadhi** [comment]
yes you are right , anyways i lwill use reflection.But then i need to create a long list of ```instanceOf ``` operator check for every object.
Thanks.
