### ISSUE TITLE
Jackson: ObjectMapper closes stream after writing value

### ISSUE THREAD

**Issue by fdinoff** [msgpack/msgpack-java#233]
Currently the ObjectMapper closes the stream which means that you can't write two values to the underlying stream which mean that the following fails because the stream has been closed

```java
PipedOutputStream pipedOutputStream = new PipedOutputStream();
PipedInputStream pipedInputStream = new PipedInputStream();
pipedInputStream.connect(pipedOutputStream);

ArrayList<Object> list = new ArrayList<>();
ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
objectMapper.writeValue(pipedOutputStream, list);
objectMapper.writeValue(pipedOutputStream, list);
```

with an IOException saying the pipe closed (same happens with socket)

```java
java.io.IOException: Pipe closed
	at java.io.PipedInputStream.checkStateForReceive(PipedInputStream.java:260)
	at java.io.PipedInputStream.receive(PipedInputStream.java:226)
	at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
	at org.msgpack.core.buffer.OutputStreamBufferOutput.flush(OutputStreamBufferOutput.java:46)
	at org.msgpack.core.MessagePacker.flush(MessagePacker.java:134)
	at org.msgpack.core.MessagePacker.close(MessagePacker.java:143)
	at org.msgpack.jackson.dataformat.MessagePackGenerator.close(MessagePackGenerator.java:344)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:2883)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2304)
```

For now I'm writing to a temporary array and then writing that value to the stream, but that seems inefficient.

```java
byte[] buffer = objectMapper.writeValueAsBytes(packet);

OutputStream output = <from somewhere>
output.write(buffer);
output.flush();
```

Would it be possible to leave the stream open after writing the value?

**Comment by komamitsu** [comment]
@fdinoff  By this PR https://github.com/msgpack/msgpack-java/pull/239, you can disable `Feature.AUTO_CLOSE_TARGET` like this:

```
        MessagePackFactory messagePackFactory = new MessagePackFactory();
        messagePackFactory.disable(JsonGenerator.Feature.AUTO_CLOSE_TARGET);
        ObjectMapper objectMapper = new ObjectMapper(messagePackFactory);
```

**Comment by fdinoff** [comment]
Enabling and disabling features doesn't seem to do anything. The test passes whether the `messagePackFactory.disable(JsonGenerator.Feature.AUTO_CLOSE_TARGET);` is enabled or disabled. 

Could you also add that check so that readValue does the same thing? (I think it just add the check inside MessagePackParser)

**Comment by komamitsu** [comment]
Good catch! I'll take care of it later.

**Comment by komamitsu** [comment]
@fdinoff I fixed the bug that changed wrong feature flag. Also you can call `readValue` more than once with `AUTO_CLOSE_SOURCE`, I think.

**Comment by fdinoff** [comment]
Thank you, This seems to work.

**Comment by borice** [comment]
Leaving a comment for future Googlers looking for a solution to the auto-closed stream:
```
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.databind.ObjectMapper;

JsonFactory jsonFactory = new JsonFactory();
jsonFactory.configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false);
ObjectMapper mapper = new ObjectMapper(jsonFactory);

// use mapper as needed... it won't automatically close your stream anymore.
```

**Comment by Sergey123456** [comment]
Does not work!
![2019-07-08_20-11-05](https://user-images.githubusercontent.com/22378271/60829178-08339580-a1bd-11e9-946c-06edd7722eec.jpg)

**Comment by komamitsu** [comment]
@Sergey123456 Your code doesn't seem to use msgpack-java....

**Comment by AaronSharp5** [comment]
Adding to @borice comment to address @Sergey123456 issue, which I also encountered:
In addition to `JsonGenerator.Feature.AUTO_CLOSE_TARGET`, which controls `OutputStream`s when serializing `Object` to JSON, there is another feature, `JsonParser.Feature.AUTO_CLOSE_SOURCE`, which controls `InputStream`s when deserializing JSON to `Object`. So if you want to handle closing both `Input-` and `OutputStream`s yourself:

```
import com.fasterxml.jackson.core.JsonFactory;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.ObjectMapper;

JsonFactory jsonFactory = new JsonFactory();
jsonFactory.configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false);
jsonFactory.configure(JsonParser.Feature.AUTO_CLOSE_SOURCE, false);
ObjectMapper mapper = new ObjectMapper(jsonFactory);

// use mapper as needed... it won't automatically close output OR input streams anymore.
```
