### ISSUE TITLE
Mixing Jackson api and value api

### ISSUE THREAD

**Issue by fdinoff** [msgpack/msgpack-java#235]
The Jackson api requires that entire format of the message to be known ahead of time. However I don't know the type until after I have deserialized part of the message. (I'm implementing a [MessagePackRPC ][rpc] client). 

For example for the [response][response], I need to deserialize an array in the format

    [type, msgid, error, result]

However I do not know the type of result until after I have parsed the msgid from the array. So I end up with a Value object for the result. At this point I know its type and would like to pass it to an ObjectMapper so it can be deserialized.

To do this I use `value.writeTo` to convert the Value object back into a byte array. After I have the byte array I then pass it to an ObjectMapper to be deserialized. This is wasteful since the value is being serialized again.

Would it be possible to either pass the value object to an ObjectMapper (and have the jackson api manipulate the Value object) or get the byte array that represented the Value object when you deserialized it the first time.

   [rpc]: https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md
   [response]: https://github.com/msgpack-rpc/msgpack-rpc/blob/master/spec.md#response-message

**Comment by komamitsu** [comment]
Sorry for the late reply. In this case, you can use `JsonNode` instead of `Value` like this:

```
    ObjectMapper mapper = new ObjectMapper(new MessagePackFactory());
    JsonNode jsonNode = mapper.readTree(inputStream);
    int msgid = jsonNode.get(1).asInt();
    JsonParser jsonParser = jsonNode.get(3).traverse();
    switch (msgid) {
        case 0:
            User user = mapper.readValue(jsonParser, User.class);
                :
            break; 
        case 1:
            Group group = mapper.readValue(jsonParser, Group.class);
                :
            break;
        :
```

**Comment by fdinoff** [comment]
For this use case that seems like it could work. Let me try it and get back to you.

**Comment by fdinoff** [comment]
This seems to work for this use case. I still think It would be nice to mix the two apis. I don't feel like the `JsonNode` represents the data type underneath properly. Especially when the `JsonNode` is representing an object. Message Pack maps can have arbitrary keys, However JSON can only have Strings for keys

**Comment by fdinoff** [comment]
Nevermind, This doesn't actually work for this use case. The library I am interfacing with encodes all strings as binary. When converting the MessagePacked Map to a JsonNode information is lost inside of the maps, which makes object deserialization fail later on.

```java
byte[] field = "field".getBytes();
ByteArrayOutputStream out = new ByteArrayOutputStream();
MessagePack.newDefaultPacker(out)
        .packMapHeader(1)
        .packBinaryHeader(field.length).writePayload(field)
        .packInt(12)
        .close();

Value value = MessagePack.newDefaultUnpacker(out.toByteArray()).getCursor().next();
System.out.println(value);

ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
JsonNode jsonNode = objectMapper.readTree(out.toByteArray());
System.out.println(jsonNode);
```

The output from running the above is
```
{field:12}
{}
```

**Comment by komamitsu** [comment]
Thanks for reporting it. Maybe it can be fixed in `MessagePackParser`. I'll check it later.

**Comment by komamitsu** [comment]
@fdinoff The issue was fixed in https://github.com/msgpack/msgpack-java/commit/2242fe497b88c6add197b67ffd46a71e926ff593.

**Comment by fdinoff** [comment]
Thank you. I'll take a look at it sometime this week.

**Comment by fdinoff** [comment]
@komamitsu this seems to work. Thank you.

The only cases where it doesn't work are in #244
