### ISSUE TITLE
what's the differences between msgpack-java v0.6 and v0.7?

### ISSUE THREAD

**Issue by BrentHuang** [msgpack/msgpack-java#247]
My code is as following:
public class LoginReq {
    private int vendor;
    private String account;

    public LoginReq() {}
    
    public LoginReq(int vendor, String account) {
        this.vendor = vendor;
        this.account = account;
    }

    public int getVendor() {
        return vendor;
    }

    public void setVendor(int vendor) {
        this.vendor = vendor;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }
}

public class Test {
    public static void main(String[] args) throws Exception {
        LoginReq loginReq = new LoginReq(1000, "123456");

        // msgpack 0.6
        org.msgpack.MessagePack pack = new org.msgpack.MessagePack();
        pack.register(LoginReq.class);
        byte[] packData6 = pack.write(loginReq);
        LoginReq unpackData6 = pack.read(packData6, LoginReq.class);
        
        // msgpack 0.7
        ByteArrayOutputStream packData7 = new ByteArrayOutputStream();
        MessagePacker packer = MessagePack.newDefaultPacker(packData7);
        packer.packInt(loginReq.getVendor());
        packer.packString(loginReq.getAccount);
        packer.close();
    }
}

I found the pack result of v0.6 and v0.7 is different, 
packData6：                      [-110, -51, 3, -24, -90, 49, 50, 51, 52, 53, 54]
packData7.toByteArray()：         [-51, 3, -24, -90, 49, 50, 51, 52, 53, 54]

the result of v0.6 is the same with c++ and python pack result, but v0.7's pack result missing one byte at the head. what's wrong?

**Comment by xerial** [comment]
Writing object in v0.6 packs object fields within array type, but your code for v0.7 just writes object parameters. If you use packArrayHeader(2) in v0.7, it will give the same result.
