### ISSUE TITLE
Suggest way to Upgrade to Jackson 2.5.4

### ISSUE THREAD

**Issue by Anand-J-Kadhi** [msgpack/msgpack-java#267]
Hello ,

I was facing an exception :: https://github.com/msgpack/msgpack-java/issues/226

For that i got an answer :: https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson

so i am using the dependency ::

><dependency>
  <groupId>org.msgpack</groupId>
  <artifactId>jackson-dataformat-msgpack</artifactId>
  <version>0.7.0-p9</version>
></dependency>

after that i was facing below exception :: 
https://github.com/FasterXML/jackson-module-mrbean/issues/24

in one of the answer it is suggested that i should  upgrade to Jackson 2.5.4

but unfortunately the dependency 

><dependency>
  <groupId>org.msgpack</groupId>
  <artifactId>jackson-dataformat-msgpack</artifactId>
  <version>0.7.0-p9</version>
>
</dependency>

internally uses Jackson 2.4.4 . Can you please suggest me any solution for this ? or anyhow can i upgrade to this version.

**Comment by komamitsu** [comment]
Can you try 0.7.0-M6 for now? It uses Jackson 2.5.3. We'll update the version to 2.5.4 later.

**Comment by Anand-J-Kadhi** [comment]
Thanks @komamitsu i will upgrade to the suggested version.
Meanwhile, want to discuss that i am facing issue while deserialization and i am completely stuck and having no clue why it comes.

The issue is i am getting below exception when deserializing an object ::

JsonMappingException: Can not instantiate value of type [simple type, ]from Integral number (60); no single-int-arg constructor/factory method
I have observed that the byte stream i am passing while deserializing the same object is like
>> 
[60, 99, 111, 109, 46, 115, 112, 114, 105, 110, 116, 46, 118, 115, 98, 46, 101, 118, 101, 110, 116, 77, 97, 110, 97, 103, 101, 114, 46, 101, 118, 101, 110, 116, 115, 46, 82, 79, 67, 111, 110, 118, 101, 114, 115, 97, 116, 105, 111, 110, 67, 114, 101, 97, 116, 101, 100, 69, 118, 101, 110, 116, 62, .............................................. and so on.
>>
where first number is 60 and it assumes of the type integer whereas the class didn't have any constructor having integer value.

Can you suggest some pointers.

**Comment by Anand-J-Kadhi** [comment]
Hi @komamitsu,

Please ignore the above exception as on analysis i found that it is xml data which was being tried to deserialized. Closing the issue and marking as invalid , sorry for the inconvinience caused.
