### ISSUE TITLE
why unsupportedOperationException thrown directly when using WriteValueAsString?

### ISSUE THREAD

**Issue by Anand-J-Kadhi** [msgpack/msgpack-java#269]
Hi,

I am using the following dependency for msgpack
```
	<dependency>
			<groupId>org.msgpack</groupId>
			<artifactId>jackson-dataformat-msgpack</artifactId>
			<version>0.7.0-M6</version>
		</dependency>
```
 And i am passing the msgpack instance to ObjectMapper
```
ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
```

I am trying to use method writeValuesAsString of the objectMapper by using method ::
```
  myString= (String) objectMapper.writeValueAsString(object);
```
this goes to the ```com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(Object) ```
method on line number 2338 then it delegates the responsibility to msgpack class ``` org.msgpack.jackson.dataformat.MessagePackFactory.createGenerator(Writer) ``` there i see directly ```UnsupportedOperationException```  is thrown, can i know why it is so ?

```
    @Override
    public JsonGenerator createGenerator(Writer w) throws IOException {
        throw new UnsupportedOperationException();
    }
```
I am not able to write the value as string due to this.Please let me know.

**Comment by komamitsu** [comment]
MessagePack is a binary serialization format and can't be represented in text format.

**Comment by bosphere** [comment]
imho exactly because it's in binary serialization format, being able to get a readable JSON string from writeValueAsString before actually writeValueAsBytes will greatly help in the debugging process. Or is there any other way to visualize the content being encoded?

**Comment by komamitsu** [comment]
@bosphere You can use `com.fasterxml.jackson.databind.ObjectMapper#writeValueAsString` with default JsonFactory like this:
```
    X foo = new X("foo", 42);
    ObjectMapper mapper = new ObjectMapper();
    System.out.println(mapper.writeValueAsString(foo));

>>> {"name":"foo","age":42}
```
