### ISSUE TITLE
MessagePackerGenerator handling BigDecimal badly

### ISSUE THREAD

**Issue by szetheli** [msgpack/msgpack-java#278]
Discovered this when experimenting with using MsgPack to serialize a JAXB generated message.
java.lang.IllegalArgumentException: MessagePack cannot serialize a BigDecimal that can't be represented as double. 33.40
at org.msgpack.jackson.dataformat.MessagePackGenerator.packBigDecimal(MessagePackGenerator.java:200)
at org.msgpack.jackson.dataformat.MessagePackGenerator.packValue(MessagePackGenerator.java:173)
at org.msgpack.jackson.dataformat.MessagePackGenerator.packObject(MessagePackGenerator.java:216)

This made me take a deeper look at the packBigDecimal function.

If instead trying to represent a BigDecimal as double or a BigInteger, you can store anything BigDecimal represents by doing:
messagePacker.packBigInteger(decimal.unscaledValue());
messagePacker.packInteger(decimal.scale());

**Comment by komamitsu** [comment]
@szetheli 
Could you give me an example code that can reproduce the error?
BTW, a value serialized as BigInteger and Integer can't be deserialized by other user. It's cause an incompatible issue, I think.

**Comment by komamitsu** [comment]
@szetheli Fixed the issue. Thanks for reporting it!
