### ISSUE TITLE
Fields Order in generated class file may be change by javac

### ISSUE THREAD

**Issue by kevin-nazgul** [msgpack/msgpack-java#298]
I use msgpack in my android project, and I use msgpack like this:
```java
@Message
public static class EmojiStruct {
	public String prefix;
	FlavorItem[] flavorItems;
	public String background;
}
```

I disassembling its class to smali:
```smali
...

.field public background:Ljava/lang/String;

.field flavorItems:[Lcom/lemon/faceu/emoji/EmojiManager$FlavorItem;

.field public prefix:Ljava/lang/String;

...
```

As you see, fields order may be change by javac. So data serialized by old version class may not deserialize by new version.

The [Binary Compatibility chapter of the Java Language Specification](http://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html) is explicit about the fact that reordering of elements in the class files is permitted:

>[...] here is a list of some important binary compatible changes that the Java programming language supports:
>
>[...]
>Reordering the fields, methods, or constructors in an existing type declaration.
>[...]
>Reordering the list of direct superinterfaces of a class or interface.

**Comment by xerial** [comment]
As you mentioned, there is no guarantee that JVM returns stable field orders. In v07, you can use msgpack-jackson for serialize/deserializing objects. Jackson has an option to sort fields alphabetically.  
`objectMapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);`

**Comment by kevin-nazgul** [comment]
Thanks!
I also use proguard to obscure my class, so the field's name is no guarantee. Maybe i should use `index` annotation to solve this. But I suggest that have some warning in docs, so other users don't encounter this issue.

**Comment by xerial** [comment]
That's nice idea. Thanks for the suggestion.
