### ISSUE TITLE
messagePack for java bean process

### ISSUE THREAD

**Issue by PGDream** [msgpack/msgpack-java#354]
我先定义一个java bean，我通过MessagePack.pack方法把List bean 序列化，但是我通过MessagePack.unpack方法时不成功报错
错误信息如下:
Exception in thread "main" org.msgpack.MessageTypeException: org.msgpack.MessageTypeException: Expected raw value, but got array value

**Comment by komamitsu** [comment]
@PGDream Could you paste your code here that reproduces this error?

**Comment by komamitsu** [comment]
I'm closing this issue. If you still have this issue, please reopen it.
