### ISSUE TITLE
MapValue to org.jon.JSONObject

### ISSUE THREAD

**Issue by behrad** [msgpack/msgpack-java#369]
I have a msgpack encoded JSON with msgpack in another languages. In java I'm getting the MapValue via msgpack-java, however I need to convert it to `org.json.JSONObject` since keys are not statically known.

**Comment by komamitsu** [comment]
I'm not sure I understand correctly, but it sounds you can get keys from MapValue like this.
```
        ImmutableValue v = MessagePack.newDefaultUnpacker(bytes).unpackValue();
        for (Map.Entry<Value, Value> kv : v.asMapValue().entrySet()) {
            System.out.println("key=" + kv.getKey() + ", value=" + kv.getValue());
        }
```

**Comment by komamitsu** [comment]
I'm closing this issue for now. If you still have this issue, please reopen it.
