### ISSUE TITLE
Make latest version available in Maven Central?

### ISSUE THREAD

**Issue by johann-petrak** [msgpack/msgpack-java#370]
The latest release here on GitHub is 0.8.7, but the latest release available through Maven Central is 0.6.12. Is there any reason why more recent versions are not available through Maven Central?

**Comment by johann-petrak** [comment]
Oh, it turns out this is available already: 
  http://search.maven.org/#search%7Cga%7C1%7Cjackson-dataformat-msgpack
However, the link to Maven central in the QuickStart Wiki page links to here
  http://repo1.maven.org/maven2/org/msgpack/msgpack/
Maybe it should link to
  http://repo1.maven.org/maven2/org/msgpack/jackson-dataformat-msgpack/
instead?

**Comment by johann-petrak** [comment]
(and also the example Maven dependency code get updated?)

**Comment by xerial** [comment]
Thanks for reporting. The quick start page was forgotten to update. I'll delete this. Thanks
