### ISSUE TITLE
Unexpected UTF-8 encoder state

### ISSUE THREAD

**Issue by Romanow** [msgpack/msgpack-java#371]
In org.msgpack:jackson-dataformat-msgpack:0.8.7 method MessagePacker::packString throw `IllegalArgumentException("Unexpected UTF-8 encoder state")` (line number 560).
In happens when string to encode less 2^16 and encoded string is greater then 2^16. In condition `written >= (1 << 32)` variable `written` has type `int` and condition `1 << 32` evaluates to 1 because 1 is `long` and there are type overflow.

**Comment by komamitsu** [comment]
@Romanow Sorry for my late reply. Could you show me a reproducible code?

**Comment by frsyuki** [comment]
#375 fixes this issue.
