### ISSUE TITLE
Pack JsonObject Android

### ISSUE THREAD

**Issue by LeonKarabchevsky** [msgpack/msgpack-java#379]
I have a JsonObject that contains several JsonArrays:
{
    "key1" : [[1, 2, 3, 4]],
    "key2" : [[1, 2, 3, 4]]
}
I would like to pack it using MessagePack without using the JsonObjects string representation,
Is it possible ?

**Comment by komamitsu** [comment]
You mean org.json.simple.JSONObject by `JsonObject `. If so, how about like this?
```
    JSONObject jsonObject;
        :

    ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
    Map<String, Object> v = objectMapper.convertValue(jsonObject, new TypeReference<Map<String, Object>>() {});
    byte[] bytes = objectMapper.writeValueAsBytes(v);
```

**Comment by komamitsu** [comment]
I'm closing this issue for now. If you still have this issue, please reopen it.
