### ISSUE TITLE
MessageInsufficientBufferException

### ISSUE THREAD

**Issue by LeonKarabchevsky** [msgpack/msgpack-java#386]
im trying to unpack data using:
 MessageUnpacker unpacker = MessagePack.newDefaultUnpacker(data);
 String data = unpacker.unpackValue().toJson();
 unpacker.close();

This randomly throws a MessageInsufficientBufferException even though the buffer size is much greater them the data length
What could be the issue ?

**Comment by xerial** [comment]
One of the possibilities is:
- `data` may contain invalid data that doesn't follow msgpack spec (e.g., too long string/array/map length is specified, but the buffer size is smaller than that)

**Comment by komamitsu** [comment]
Closing this issue for now. If you still have this issue, please reopen it.
