### ISSUE TITLE
Jackson silently re-types Integer Map keys

### ISSUE THREAD

**Issue by FullyArticulate** [msgpack/msgpack-java#390]
`
Map<Integer,Object> map
`
gets silently encoded as
`
Map<String,Object> map
`

Because JSON doesn't allow map keys to be anything but Strings (and Jackon is fundamentally just a JSON encoder with this msgpack stuff hacked on), Jackson silently replaces the integer key with a string and it gets encoded that way in msgpack. Aside from the waste of space encoding a string instead of a simple int, it's probably not a big deal for Java->Java Jackson based encoding.

However, if you're sending msgpack messages to other languages, expect some significant problems.

**Comment by komamitsu** [comment]
@FullyArticulate 
You can use `MessagePackSerializerFactory` in this case like this
```
ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
objectMapper.setSerializerFactory(new MessagePackSerializerFactory());
Map<Integer, String> map = new HashMap<>();
map.put(1, "one");
map.put(2, "two");
byte[] bytes = objectMapper.writeValueAsBytes(map);
        // >>> [-126, 1, -93, 111, 110, 101, 2, -93, 116, 119, 111]
```
```
$ ruby -rmsgpack -e "p MessagePack.unpack([-126, 1, -93, 111, 110, 101, 2, -93, 116, 119, 111].pack('C*'))"
{1=>"one", 2=>"two"}
```

**Comment by komamitsu** [comment]
Closing this issue for now. If you still have this issue, please reopen it.

**Comment by weii41392** [comment]
Has this behavior changed? I got a different result using the code snippet:

```
ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
objectMapper.setSerializerFactory(new MessagePackSerializerFactory());

Map<Integer, String> map = new HashMap<>();
map.put(1, "one");
map.put(2, "two");

byte[] bytes = objectMapper.writeValueAsBytes(map);
System.out.println(Arrays.toString(bytes)); // Got [-126, -95, 49, -93, 111, 110, 101, -95, 50, -93, 116, 119, 111]
```

It seems that map keys are converted into strings.
