### ISSUE TITLE
Missing capacity check for addPayload in MessagePacker

### ISSUE THREAD

**Issue by bruceleexiaokan** [msgpack/msgpack-java#395]
There's no capacity check in addPayload method. So when the payload size is larger than buffer size, it won't be able to resize the buffer to make sure the capacity.

**Comment by komamitsu** [comment]
@bruceleexiaokan 
`MessagePacker#addPayload` checks the remaining size and so on https://github.com/msgpack/msgpack-java/blob/develop/msgpack-core/src/main/java/org/msgpack/core/MessagePacker.java#L1007.

```
        if (buffer == null || buffer.size() - position < len || len > bufferFlushThreshold) {
            flush();  // call flush before add
            // Directly add the payload without using the buffer
            out.add(src, off, len);
            totalFlushBytes += len;
        }
        else {
            buffer.putBytes(position, src, off, len);
            position += len;
        }
```

> when the payload size is larger than buffer size

In this case, MessagePacker flushes data in `buffer` and then writes data passed as an argument to output stream or something directly.

**Comment by komamitsu** [comment]
Closing this issue for now. If you still have this issue, please reopen it.
