### ISSUE TITLE
Map serialization cannot find templates for Object classes

### ISSUE THREAD

**Issue by mgenov** [msgpack/msgpack-java#4]
Hello, 
It seems that map serialization fails when Map contains an Object values. Here is the full stack trace and the code that is causing this error:

org.msgpack.MessageTypeException: Cannot find template for class java.lang.Object class. Try to add @Message annotation to the class or call MessagePack.register(Type).
    at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:220)
    at org.msgpack.template.TemplateRegistry.lookupGenericTypeImpl(TemplateRegistry.java:258)
    at org.msgpack.template.TemplateRegistry.lookupGenericType(TemplateRegistry.java:230)
    at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:180)

``` java
package com.mycompany.app;

import org.junit.Test;
import org.msgpack.MessagePack;
import org.msgpack.annotation.Message;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import static junit.framework.Assert.assertEquals;

/**
 * Verifies whether object that contains map string -> object could be serialized.
 */
public class SerializeEntityWithMapTest {

  @Message
  public static class Entity {
    public String name;
    public Map<String, Object> properties = new HashMap<String, Object>();
  }

  @Test
  public void happyPath() throws IOException {
    MessagePack pack = new MessagePack();

    Entity e = new Entity();
    e.name = "test";
    e.properties.put("Test","aaaa");

    byte[] content = pack.write(e);

    Entity actual = new MessagePack().read(content, Entity.class);

    System.out.println(actual.properties);
    assertEquals(1,actual.properties.size());
  }
}


```

**Comment by hangsucho** [comment]
```
toObject() {
...
  } else if (value.isMapValue()) { // Map
 MapValue v = value.asMapValue();
 Map ret = new HashMap(v);
 return ret;
...
}
```

**Comment by rmckinnon** [comment]
I modified the toObject method to address the "isMapValue" condition:

private static Object toObject(Value value) throws IOException {
        Converter conv = new Converter(value);
        if (value.isNilValue()) { // null
            return null;
        } else if (value.isRawValue()) { // byte[] or String or maybe Date?
            // deserialize value to String object
            RawValue v = value.asRawValue();
            return conv.read(Templates.TString);
        } else if (value.isBooleanValue()) { // boolean
            return conv.read(Templates.TBoolean);
        } else if (value.isIntegerValue()) { // int or long or BigInteger
            // deserialize value to int
            IntegerValue v = value.asIntegerValue();
            return conv.read(Templates.TInteger);
        } else if (value.isFloatValue()) { // float or double
            // deserialize value to double
            FloatValue v = value.asFloatValue();
            return conv.read(Templates.TDouble);
        } else if (value.isArrayValue()) { // List or Set
            // deserialize value to List object
            ArrayValue v = value.asArrayValue();
            List<Object> ret = new ArrayList<Object>(v.size());
            for (Value elementValue : v) {
                ret.add(toObject(elementValue));
            }
            return ret;
        } else if (value.isMapValue()) { // Map
            // deserialize value to Map object
            MapValue mv = value.asMapValue();
            Map<String, Object> map = new LinkedHashMap<String, Object>();
            for (Value key: mv.keySet()) {
                map.put(new Converter(key).read(Templates.TString), toObject(mv.get(key)));
            }

            return map;
        } else {
            throw new RuntimeException("fatal error");
        }
    }
