### ISSUE TITLE
perl message send to redis and unpackable by java

### ISSUE THREAD

**Issue by omarhaq** [msgpack/msgpack-java#400]
I have packed a message using perl msgpack and sent it to a redis channel. I am trying to unpack it using java message pack with jedis. I'm not having much success and the unpacker is only seeing an Integer object. Is this impossible?
```
my $mp = Data::MessagePack->new();
my $msgstr = $mp->encode($message);
$conn->publish($channel, $msgstr);

```
Java:
```

class Subscriber extends JedisPubSub
{
    public void onMessage(String channel, String message)
    {
	MessageUnpacker unpacker = MessagePack.newDefaultUnpacker(message.getBytes());

```
Only unpacker.unpackInt() returns a value and its -17. I am able to subscribe to the channel using python and using the python messagepack library.

**Comment by komamitsu** [comment]
@omarhaq 
MessagePack is a binary format and should be handled as a byte array. So the String `message` in `onMessage()` would be converted unexpectedly and you can't handle it properly, I guess.

**Comment by komamitsu** [comment]
Closing this issue. Please reopen if you still have the issue.

**Comment by omarhaq** [comment]
Sorry for the delay. So I got the unpacking to work more or less. I am having trouble with unpacking the compressed binary message. I lose the first line of my message after I decompress. 



> int length = unpacker.unpackBinaryHeader();
> 	byte[] unpackedArray = unpacker.readPayload(length);
> 	Inflater decompresser = new Inflater();
> 	decompresser.setInput(unpackedArray);
> 	byte[] decompressedArray = new byte[length * 20];
> 	decompresser.inflate(decompressedArray);
> 	decompresser.end();
> 	return new String(decompressedArray, "UTF-8");

**Comment by Gajanana** [comment]
@omarhaq I am facing same issue can you please provide working code reference if possible . Thank you .
