### ISSUE TITLE
Deserializing collections with interface/abstract type parameter fails

### ISSUE THREAD

**Issue by mikolak-net** [msgpack/msgpack-java#41]
Recently I'm stumped with a scenario where I deserialize a collection having a generic type parameter that is an interface causes an exception. Example:

````java
import java.util.HashSet;
import java.util.Set;

public class A {

	private Set<C> cs;
	
	public A() {
		cs = new HashSet<C>();
	}

	public Set<C> getCs() {
		return cs;
	}

	public void setCs(Set<C> cs) {
		this.cs = cs;
	}
	
	public void addC(C c) {
		cs.add(c);
	}
	
}

public interface C {

}

public class B implements C {

	private int number;

	public int getNumber() {
		return number;
	}

	public void setNumber(int number) {
		this.number = number;
	}
	
}
````

Calling this:

````java
A a = new A();
B b = new B();
b.setNumber(1);
a.addC(b);

MessagePack msgPack = new MessagePack();
msgPack.register(B.class);
msgPack.register(A.class);

A newA = msgPack.read(msgPack.write(a),A.class);
````

results in a *org.msgpack.MessageTypeException* in *AnyTemplate*.

**Do I really need to write a custom template for this? Shouldn't this be supported out of the box?**

**Comment by komamitsu** [comment]
> Re 3. Do you mean something like the @JsonTypeInfo annotation? If so, this would indeed solve the problem.

@mikolak-net @QuickUnit We added https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson and it would solve this sort of problem.

**Comment by komamitsu** [comment]
I'm closing this issue. Please re-open it if you still have any problem.
