### ISSUE TITLE
MessageBuffer.allocate and reflection

### ISSUE THREAD

**Issue by DGolubets** [msgpack/msgpack-java#411]
Is it really necessary?
Cos it looks very slow in profiler.

**Comment by xerial** [comment]
Yes. This is necessary to avoid loading any sub classes extending MessageBuffer (e.g., MessageBufferBE).  If we have multiple implementations of MessageBuffer methods, each method call (e.g., readInt, xxx) will have overhead for resolving the concrete methods. 

For example, simply importing MessageBufferBE in the class header will slow down the performance.

**Comment by xerial** [comment]
Compared to MessageBuffer.allocate, calling MessageBuffer.read/writeXXX is much more frequent. So this is a design choice.
