### ISSUE TITLE
@Message before class can not compile

### ISSUE THREAD

**Issue by kspham** [msgpack/msgpack-java#413]
Hi, 
I followed the doc of msgpack-java here: https://gist.github.com/thiagozs/6699612 and defined my message: 
     @Message //Annotation
     public static class MyMessage
     {
         public String name;
         public double version;
     }   

but seems that this Annotation is not supported? 

This is the compile error: 
[error] /Users/son/code/msgpack-java/msgpack-core/src/test/java/org/msgpack/core/example/MessagePackExample.java:42: cannot find symbol
[error]   symbol:   class Message
[error]   location: class org.msgpack.core.example.MessagePackExample
[error]     @Message //Annotation
[error] (msgpack-core/test:compileIncremental) javac returned nonzero exit code
[error] Total time: 2 s, completed Mar 11, 2017 12:57:13 AM

**Comment by komamitsu** [comment]
`@Message` is available in v0.6 or earlier.

Current version doesn't support it. Instead you can use Jackson annotation. https://github.com/msgpack/msgpack-java/tree/develop/msgpack-jackson
