### ISSUE TITLE
Cross Platform Usage Problem

### ISSUE THREAD

**Issue by subliz** [msgpack/msgpack-java#417]
I am using msgPack (https://github.com/deniszykov/msgpack-unity3d/tree/master/GameDevWare.Serialization.Unity/Assets/Plugins/GameDevWare.Serialization) in unity with .Net for online game and serialize objects to send over the net to back-end server application which developed in java, and I pack this class for example : 

    public class MsgPackTestClass  {

        public int stringManipulationForProgrammers;
        public int stringManipulationForProgrammers2;
        public int stringManipulationForProgrammers3;

        public MsgPackTestClass()
        {}
    }

with this values : 

    var m = new MsgPackTestClass();
        m.stringManipulationForProgrammers = 15; 
        m.stringManipulationForProgrammers2 = 255; 
        m.stringManipulationForProgrammers3 = 65537; 

      var s = new MemoryStream();                
      MsgPack.Serialize<MsgPackTestClass>(m, s , SerializationOptions.SuppressTypeInformation );

and finally i got this byte array ( hex converted ) : 

`83d920737472696e674d616e6970756c6174696f6e466f7250726f6772616d6d6572730fd921737472696e6   74d616e6970756c6174696f6e466f7250726f6772616d6d65727332d1ff00d921737472696e674d616e6970756c6174696f6e466f7250726f6772616d6d65727333d201000100`

and java using this library packing same class with same values got this byte array : 

      MsgPackTestClass msgPackTestClass = new MsgPackTestClass();

      msgPackTestClass.setStringManipulationForProgrammers(15);
      msgPackTestClass.setStringManipulationForProgrammers2(255);
      msgPackTestClass.setStringManipulationForProgrammers3(65537);

      ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());

      byte[] bytes = objectMapper.writeValueAsBytes(msgPackTestClass);

`
83D920737472696E674D616E6970756C6174696F6E466F7250726F6772616D6D6572730FD921737472696E674D616E6970756C6174696F6E466F7250726F6772616D6D65727332CCFFD921737472696E674D616E6970756C6174696F6E466F7250726F6772616D6D65727333CE00010001`

which is different with mine and we have problems in decode class objects.
why these two libraries pack the same class ( and values ) in different way ? 
also please guide me how to use msgPack in cross-platform way between java and C# ? 
thank you in advance...

**Comment by komamitsu** [comment]
The encoded byte arrays can be deserialized with MessagePack Ruby implementation as follows

* MessagePack data serialized with C# implementation (the first one)
```
irb(main):013:0* MessagePack.unpack([0x83, 0xd9, 0x20, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x6e, 0x69, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x73, 0x0f, 0xd9, 0x21, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x6e, 0x69, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x73, 0x32, 0xd1, 0xff, 0x00, 0xd9, 0x21, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4d, 0x61, 0x6e, 0x69, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x6d, 0x65, 0x72, 0x73, 0x33, 0xd2, 0x01, 0x00, 0x01, 0x00].pack('C*'))
=> {"stringManipulationForProgrammers"=>15, "stringManipulationForProgrammers2"=>-256, "stringManipulationForProgrammers3"=>16777472}
```

*  MessagePack data serialized with Java implementation (the second one)
```
irb(main):010:0* MessagePack.unpack([0x83, 0xD9, 0x20, 0x73, 0x74, 0x72, 0x69, 0x6E, 0x67, 0x4D, 0x61, 0x6E, 0x69, 0x70, 0x75, 0x6C, 0x61, 0x74, 0x69, 0x6F, 0x6E, 0x46, 0x6F, 0x72, 0x50, 0x72, 0x6F, 0x67, 0x72, 0x61, 0x6D, 0x6D, 0x65, 0x72, 0x73, 0x0F, 0xD9, 0x21, 0x73, 0x74, 0x72, 0x69, 0x6E, 0x67, 0x4D, 0x61, 0x6E, 0x69, 0x70, 0x75, 0x6C, 0x61, 0x74, 0x69, 0x6F, 0x6E, 0x46, 0x6F, 0x72, 0x50, 0x72, 0x6F, 0x67, 0x72, 0x61, 0x6D, 0x6D, 0x65, 0x72, 0x73, 0x32, 0xCC, 0xFF, 0xD9, 0x21, 0x73, 0x74, 0x72, 0x69, 0x6E, 0x67, 0x4D, 0x61, 0x6E, 0x69, 0x70, 0x75, 0x6C, 0x61, 0x74, 0x69, 0x6F, 0x6E, 0x46, 0x6F, 0x72, 0x50, 0x72, 0x6F, 0x67, 0x72, 0x61, 0x6D, 0x6D, 0x65, 0x72, 0x73, 0x33, 0xCE, 0x00, 0x01, 0x00, 0x01].pack('C*'))
=> {"stringManipulationForProgrammers"=>15, "stringManipulationForProgrammers2"=>255, "stringManipulationForProgrammers3"=>65537}
```

It looks like MessagePack C# doesn't encode 255 and 65537 correctly.

**Comment by glautrou** [comment]
I have a similar problem, any solution?
