### ISSUE TITLE
unpack question

### ISSUE THREAD

**Issue by leewcc** [msgpack/msgpack-java#432]
There is a issue that i use the messagePack pack a object(javabean) to byte array and store it. After that, i want to unpack this byte array,but i do not know the object type,can i unpack it to string(like json string) for show. If can, how should i do?

**Comment by komamitsu** [comment]
@leewcc Sorry. I missed this issue...

If you don't know the type of packed byte array, it's not easy to convert it to a POJO / JavaBean. But you can handle it as a org.msgpack.value.Value like this.

```
    public static class User {
        public String name;
        public int age;
    }

    public static void main(String[] args) throws Exception {
        ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());

        User user = new User();
        user.name = "Foo Bar";
        user.age = 42;

        byte[] bytes = objectMapper.writeValueAsBytes(user);

        Map<Value, Value> map = MessagePack.newDefaultUnpacker(bytes).unpackValue().asMapValue().map();
        System.out.println(String.format("name:%s, age:%d",
                map.get(ValueFactory.newString("name")).asStringValue().asString(),
                map.get(ValueFactory.newString("age")).asIntegerValue().asInt()));
    }
```

**Comment by komamitsu** [comment]
Closing this issue. Feel free to reopen it if needed.
