### ISSUE TITLE
API changes report for MessagePack Core

### ISSUE THREAD

**Issue by lvc** [msgpack/msgpack-java#440]
Hi,

I'd like to share report on API changes and backward compatibility for the MessagePack Core library: https://abi-laboratory.pro/java/tracker/timeline/msgpack-core/

BC — binary compatibility
SC — source compatibility

The report is generated according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2 by the https://github.com/lvc/japi-tracker tool.

Hope it will be helpful for users and maintainers of the library.

Is there a snapshot jar for the library, so I can run daily analysis for it?

Thank you.

![msgpack-core-1](https://user-images.githubusercontent.com/1517837/32478132-f01e56fa-c393-11e7-99db-e2254104ca63.png)

![msgpack-core-2](https://user-images.githubusercontent.com/1517837/32478131-f00233a8-c393-11e7-8a10-ea79638b93d1.png)

**Comment by xerial** [comment]
snapshot is also available at https://oss.sonatype.org/content/repositories/snapshots/org/msgpack/msgpack-core/ 
but currently we are not frequently using snapshot versions. 

Thanks!
