### ISSUE TITLE
Question: unpacking message with multiple item

### ISSUE THREAD

**Issue by yulrizka** [msgpack/msgpack-java#442]
I'm trying to decode data that was generated with go. The payload that contain 2 events

```
	var w bytes.Buffer

	testBatch := []Event{
		exampleEvent,
		exampleEvent,
	}

	for _, e := range testBatch {
		data, err := e.MarshalMsg(nil)
		if err != nil {
			t.Fatalf("MarshalMsg failed: %v", err)
		}
		if _, err := w.Write(data); err != nil {
			t.Fatalf("Write: %v", err)
		}
	}

       // w.Bytes() now contain bytes that java will read.
```

If I understand correctly, the result in the buffer are result for the 2nd message appended to the first.

How to read this in java with jackson? I manage to read the first message but don't know how to retrieve the second.

```
ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
Event events = objectMapper.readValue(in, Event.class);

// Event events2 = objectMapper.readValue(in, Event.class); // this doesn't work
```

got this error 
```
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: java.io.ByteArrayInputStream@2374d36a; line: -1, column: 0]
```

**Comment by komamitsu** [comment]
> // Event events2 = objectMapper.readValue(in, Event.class); // this doesn't work

@yulrizka Can you give me the error message?

BTW, `objectMapper.configure(JsonParser.Feature.AUTO_CLOSE_SOURCE, false)` might solve the issue.

https://github.com/msgpack/msgpack-java/blob/develop/msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java#L452-L454

**Comment by yulrizka** [comment]
@komamitsu I mentioned the error message above. I'll try the configuration tomorrow

**Comment by komamitsu** [comment]
Oops. I missed it...

If the configuration doesn't work, paste the bytes and `Event` class.

**Comment by komamitsu** [comment]
I'm closing this issue. If you still have any problems, feel free to reopen it
