### ISSUE TITLE
Compatibility Problem with jackson-dataformat-msgpack and msgpack v6

### ISSUE THREAD

**Issue by zeroxychn** [msgpack/msgpack-java#449]
I  upgrade my  codes from v0.6.12 to v0.8.14. for some reason, i must compatible for java pojo pack data from msgpack-v6, so i use jackson-dataformat-msgpack to deserialize  the data. but when I use jackson-dataformat-msgpack V0.8.14 to deserialize from msgpack v6 pack data, I meet  compatibility problem. 
Ps.  If the array length is more than 31, msgpack-v0.6.12 will pack the bin array to STR16  format,. like this: {0x91, 0xda, 0x00, 0x99, xx, xx, xx...}. 
This is my test codes:
```
/*Pojo Class*/
public class TestPojo {

    private byte[] aryValue;

    public byte[] getAryValue() {
        return aryValue;
    }

    public void setAryValue(byte[] aryValue) {
        this.aryValue = aryValue;
    }
}

/* Test Code*/
public class App 
{
    public static void main( String[] args ) throws IOException {
        /* data from msgpack v0.6.12*/
        byte[] str16FromV6 = new byte[154];
        str16FromV6[0] = (byte) 0x91;
        str16FromV6[1]= (byte) 0xda;
        str16FromV6[2] = 0x00;
        str16FromV6[3] = (byte) 0x96;
        for(int i=4; i<154; i++){
            str16FromV6[i] = (byte) i;
        }
        /*deserialize  with msgpack-java v.0.8.14 */
        MessageUnpacker unpacker = MessagePack.newDefaultUnpacker(str16FromV6);
        unpacker.unpackArrayHeader();
        int nlen = unpacker.unpackBinaryHeader();
        TestPojo test1 = new TestPojo();
        test1.setAryValue(new byte[nlen]);
        unpacker.readPayload(test1.getAryValue());
        System.out.println("STR16 bin_size from MessageUnpacker: " + nlen);
        System.out.println("bin head: " + test1.getAryValue()[0]);
        System.out.println("bin tail: " + test1.getAryValue()[149]);

        /*deserialize   with  jackson-dataformat-msgpack v.0.8.14*/
        ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
        objectMapper.setAnnotationIntrospector(new JsonArrayFormat());
        TestPojo test2 = objectMapper.readValue(str16FromV6, TestPojo.class);
        System.out.println("STR16 bin_size from ObjectMapper: " + test2.getAryValue().length);
        System.out.println("bin head: " + test2.getAryValue()[0]);
        System.out.println("bin tail: " + test2.getAryValue()[149]);
    }
}
``` 
The console output:
```
STR16 bin_size from MessageUnpacker: 150
bin head: 4
bin tail: -103
STR16 bin_size from ObjectMapper: 202
bin head: 4
bin tail: -65
```
So the binarray length and data deserialized by ObjectMapper is all wrong.

I refer this issue  https://github.com/msgpack/msgpack-java/issues/252 answerd by @komamitsu .

**Comment by komamitsu** [comment]
@zeroxychn Thanks for reporting this issue. This is interesting... I'll look into it later.

**Comment by komamitsu** [comment]
The byte array includes non-printable values. And the type is `str` not `bin`. So jackson-dataformat-msgpack converts the byte array to a string somehow and then it's converted to a byte array. But, in Java, those characters are represented in multiple bytes.
```
    byte[] printable = new String(new byte[] {(byte) 0x7E}).getBytes(); // => [0x7E]
    byte[] nonPrintable = new String(new byte[] {(byte) 0x80}).getBytes(); // => [0xEF, 0xBF, 0xBD]
```
This is what happened in jackson-dataformat-msgpack. So byte arrays should be serialized as `bin` type.

**Comment by zeroxychn** [comment]
@komamitsu, Thank for answering. so  jackson-dataformat-msgpack  v.8 is not  compatible with msgpack v6  completely when pojo class has byte array field.  Does this problem can only  be solved by upgrade my client from msgpack v6 to v8?

**Comment by komamitsu** [comment]
I'm closing this issue. If you still have any problems, feel free to reopen it
