### ISSUE TITLE
c# serialized file not deserializing in java and vice versa

### ISSUE THREAD

**Issue by deftsoftiphone** [msgpack/msgpack-java#462]
I am serializing a file in C# code with code 

           public class  WrapperEntry {
                  public WrapperEntry(){ }

                 public List<FileItem> ContentList { get; set; }
                 public string ContainerID { get; set; }
                 public string Version { get; set; }
           }

    public class  WrapperEntry2Serializer  : MessagePackSerializer<Guid>
    {
        public WrapperEntry2Serializer(SerializationContext ownerContext) : base(ownerContext) { }

        protected override void PackToCore(Packer packer, Guid entry)
        {
            string s = entry.ToString();
            packer.Pack(s);
        }

        protected override Guid UnpackFromCore(Unpacker unpacker) {
            var unpacked = unpacker.LastReadData;
            string s = unpacked.ToString();
            return new Guid(s);
            }
   }

       public static bool WriteToBinayFile(string destinationPath, WrapperEntry containerItem) {
            try  {
                var context = new SerializationContext(PackerCompatibilityOptions.None);
                context.Serializers.RegisterOverride(new WrapperEntry2Serializer(context));
                context.SerializationMethod = SerializationMethod.Map;
                using (Stream stream = File.Open(destinationPath, FileMode.Create))
                {
                    var serializer = context.GetSerializer<WrapperEntry>();
                    serializer.Pack(stream, containerItem);
                    return true;
                }	
            }
            catch { }
            return false;
        }

**In Java code:**  I am unable to deserialize file 

**liberary version :**   msgpack-0.6.12.jar

    public static WrapperEntry **readFromBinayFile**(String filePath){
        try {
            byte[] bytes = getBytesFromFile(getFile(filePath));
            MessagePackSerializer serializer = MessagePackSerializer.getInstance();
            return serializer.deserialize(bytes, WrapperEntry.class);
        }
        catch(Exception ex) {
            ex.printStackTrace();
        }
        return null;
    }

**MessagePackSerializer  Class:**

public class MessagePackSerializer implements Serializer {

    MessagePack messagePack;

    public static MessagePackSerializer getInstance() {
        return new MessagePackSerializer();
    }

    private MessagePackSerializer() {
        messagePack = new MessagePack();
    }

    @Override
    public <T> void serialize(OutputStream outputStream, T obj) throws IOException {
        registerClass(obj.getClass());
        messagePack.write(outputStream, obj);
    }

    public <T> T deserialize(byte[] source, Class<T> clazz) throws IOException {
        registerClass(clazz);
        return messagePack.read(source, clazz);
    }

    public void close() throws IOException {
        messagePack.unregister();
        messagePack = null;
    }

    private void registerClass(Class<?> clazz) {
        if (clazz.isAnnotationPresent(Message.class)) {
            return;
        }
        if (messagePack.lookup(clazz) != null) {
            return;
        }
        messagePack.register(clazz);
    }
}

please let me know if I am doing something wrong
Thanks

**Comment by komamitsu** [comment]
Unfortunately, msgpack-java v0.6 serializes objects as a key-value list. Please use current msgpack-java that serializes objects as a map like msgpack-C#
