### ISSUE TITLE
Messagepack is not compressing the data?

### ISSUE THREAD

**Issue by loosbrecht** [msgpack/msgpack-java#480]
Hello,

I'm currently trying to use MessagePack to compress JSONObjects. I need to send these JSONObjects over the network but because they are pretty big I first want to compress them with MessagePack. The problem is that I don't see any compression happening.  It's possible that I don't use the correct code, but I would really like help to get this working.

I tried the online example on your site and I got a compression of 50%, but I can't seem to get it working in Java.

The code I'm using is the following, I'm currently using a String representation of the JsonObject and not a real JsonObject. But this doesn't look like the root cause to me.(I also got problems with JSONObjects, that's why I'm using Strings for the moment)
```java
private byte[] encodeWithMsgPack(String obj) throws IOException {
		byte[] byteStr = obj.getBytes();
                System.out.println("Original size: " + byteStr.length);
		MessageBufferPacker packer = MessagePack.newDefaultBufferPacker();
		packer.packString(obj);
		packer.close();
		byte[] msgPackByte = packer.toByteArray();
		System.out.println("Message pack size " + msgPackByte.length);	
		return msgPackByte;
	}
'''
The result of this function is:
```
Original size: 1563
Message pack size 1566
```

Thanks!

**Comment by gaohao** [comment]
I think you are not using it correctly. You need to pack each field of your json object. Right now you just packed the json str into one msgpack field.

**Comment by loosbrecht** [comment]
Yes that could be the case that I'm not using it correctly. In our current implementation it isn't very easy to map every element of our json object in a seperate field because the structure isn't always the same.
This would also cost us a lot of work. Thinking about this it does sound logical to map every field seperately.

 I thought that a normal string would also be compressed with msgpack but this is maybe not the case.

In the meanwhile we found another solution so we can close this issue.
