### ISSUE TITLE
impossible to decode FIXSTR type using jackson

### ISSUE THREAD

**Issue by thinkberg** [msgpack/msgpack-java#485]
I am receiving messages which have binary data encoded as FIXSTR. However, using the jackson-dataformat-msgpack lib, it is impossible to get to the raw data in it. 

I did write a Deserializer for my data format, which works fine, except for this issue.

The decoding to String breaks the content. I think it would be helpful, if I could configure how to handle STR types even for the jackson MessagePackParser, or alternatively have access to the raw binary data.

**Comment by komamitsu** [comment]
I don't think it's a good idea to encode binary data as STR...

But I think you can handle binary data encoded as STR. This test case would help you 

https://github.com/msgpack/msgpack-java/blob/51cf272f05dffdb4a2f606831f0acf1a98f88933/msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackDataformatTestBase.java#L163-L167

https://github.com/msgpack/msgpack-java/blob/46de775c07c3a3ae9a4b131380ab407697d63eaa/msgpack-jackson/src/test/java/org/msgpack/jackson/dataformat/MessagePackParserTest.java#L763-L782

**Comment by thinkberg** [comment]
The issue is that the other side codes any kind of binary data and it cannot be decoded as valid UTF-8. So if I could configure the parser to tell it I want the binaryValue to be directly returned instead of new String(bindata).getBytes("UTF-8") would be an awesome solution.

**Comment by komamitsu** [comment]
Didn't my example code work? If not, can you paste your code to clarify your problem?

**Comment by thinkberg** [comment]
Hi @komamitsu, sorry for the delay, I do think your solution works, but I don't have POJOs for that specific case. I do receive an envelope {"a":123, "p": ["foo":"...."]} where the type foo is basically anything that is valid msgpack. If within p there is a RawStr encoded blob it will be broken. I do know whether in p may be RawStr encoded data (a is a version number), but the only way to fix the issue right now is to recurse into p and handle all RawStr encoded data by hand using the MessageUnpacker.

**Comment by thinkberg** [comment]
What I am looking for, is a way to intercept the currently hardwired way that a FIXSTR/STRx conversion is done. This is even asked for in the specification: https://github.com/msgpack/msgpack/blob/master/spec.md#limitation

```Deserializers should provide functionality to get the original byte array so that applications can decide how to handle the object```

**Comment by komamitsu** [comment]
One possible option is to add a feature flag makes jackson-dataformat-msgpack handle all STRs as `byte[]`. Do you think it works for your case? With this feature, you would get original byte array even if it's encoded as STR, but you need to receive all valid STRs as `byte[]`.

IMO, using MessageUnpaker sounds the best way for such a case, though.
