### ISSUE TITLE
Can messagepack be used for data validations in java?

### ISSUE THREAD

**Issue by shilpauran** [msgpack/msgpack-java#494]
I am getting a Json payload and this payload needs to be undergo data validations. Currently this is proved to be an in-efficient way of doing validations with many ifs and thens. So i was suggested to use MESSAGEPACK for effective validation . I have gone through many links on how to use MessagePack. Almost all the links talk about serializing and deserializing, but i failed to find a link to use messagepack for effiecient validations in java.Here i list down an input payload eg:
`{
"ProductId":"Rental_Service_100",
"ProductName":"Laptop",
"ProductType":"S",
"Status":"Active",
"TariffId":"123",
}`

using Json, currently the above payload is being validated
eg:
`JsonElement jsonElement = new JsonParser().parse(reader);
if(jsonElement.isJsonObject()) {
jsonObj = jsonElement.getAsJsonObject();
}
TaxRequest model = new Gson().fromJson(jsonObj.toString(), TaxRequest.class); "TaxRequest.class is the schema of json
if (model.getProductId() == null || model.getProductId().trim().equals("")) {
    throw new InvalidIdException("Id in the request header is missing.");
}`

This works perfectly fine now. But can the same type of validation be done by using MessagePack ? if so please help me with it. A sample validation would be much appreciated.

**Comment by komamitsu** [comment]
You can deserialize MessagePack format byte array to a POJO like https://github.com/msgpack/msgpack-java/blob/develop/msgpack-jackson/README.md#serializationdeserialization-of-pojo and then validate it.
