### ISSUE TITLE
Can not unpack byte array to get parameter name?

### ISSUE THREAD

**Issue by wuxin402** [msgpack/msgpack-java#496]
If you use messagepack to pack one java bean,when you unpack the byte array,then find the parameter name is lost.The issue maybe one bug

**Comment by wuxin402** [comment]
if you use messagepack to pack one java bean,then use nodejs to  unpack the buffer,find the parameter name is lost

**Comment by komamitsu** [comment]
I think you mentioned about the behaviour in v0.6 or earlier which serializes a POJO to an array of values.

You can use [jackson-dataformat-msgpack](https://github.com/msgpack/msgpack-java/blob/develop/msgpack-jackson/README.md) bundled in v0.7 or later which serializes a POJO to a map of key-values.
