### ISSUE TITLE
how to pack/unpack object

### ISSUE THREAD

**Issue by sayid** [msgpack/msgpack-java#502]
Excuse me.
How to pack/unpack object?
Could i use it like jsonobject？

**Comment by komamitsu** [comment]
@sayid I hope https://github.com/msgpack/msgpack-java/blob/develop/msgpack-core/src/test/java/org/msgpack/core/example/MessagePackExample.java would help you.

> jsonobject

You mean `org.json.JSONObject`, right? We don't support it, but you can use `com.fasterxml.jackson.databind.ObjectMapper` instead. See https://github.com/msgpack/msgpack-java/blob/develop/msgpack-jackson/README.md for details.
