### ISSUE TITLE
Different bytes when serializing in C# vs Java

### ISSUE THREAD

**Issue by rotter** [msgpack/msgpack-java#506]
I have a multiplatform multiplayer game which has its communication working in JSON. I was searching for a more optimized way to send/receive the data and found out about msgpack today, so bear with me if Im doing something stupid.

I migrated my whole architecture both in client (C# / Unity) and on the server (Java) to use msgpack but Im having an issue I cant figure out, I dont know if it's a bug or Im doing something wrong, and if it is a bug, I dont know on which package (Im using msgpack-java, msgpack-jackson, and MessagePack-CSharp).

After a couple hours narrowing down the problem I got to this:

I have a very simple class on both platforms with 3 attributes:
`class MyClass { int a; string b; string c;}`

If I serialize it with a certain content on C# and log it to the screen locally right after serializing, I get the following bytes (trimmed at 10 bytes):
csharp_bytes: 0x93 0x5B 0xD9 0x24 0x44 0x33 0x39 0x44 0x43 0x39

If I serialize it with the exact same content on the Java client and log it to the screen locally right after serializing, I get the following bytes (trimmed at 10 bytes):
java_bytes: 0x83 0xAD 0x63 0x6C 0x69 0x65 0x6E 0x74 0x56 0x65 0x72 0x73 0x69

If I try to deserialize "csharp_bytes" on the csharp client, it will work and I can get the fields contents correctly.

If I try to deserialize "java_bytes" on the java client, it will work and I can get the fields contents correctly.

But if I try to deserialize "csharp_bytes" on the java client it will raise an exception, saying the first byte (0x93) indicates an array (START_ARRAY token).

Am I doing something wrong? Any pointers on how to fix?

**Comment by rotter** [comment]
I tried migrating my C# code to the msgpack-cli library (I hadnt noticed it existed before creating the issue), but I obtained a similar result, with the first byte being a "0x93" causing the same problem on the Java side.

**Comment by rotter** [comment]
Ok, I was out of town for a few days, just got back today and finally got it to work. It seems that for some bizarre reason the C# side packs using one method (array) and the Java side tries to unpack using another method (map), so I have to on either side change the packing/unpacking method.

I wont close this issue as for me this is bizarrely weird for not being a bug, but feel free to close it if this is by design.

**Comment by komamitsu** [comment]
Yeah. How an object is serialized in MessagePack is different over MessagePack serialize/deserialize libraries.

Historically speaking, msgpack-java v6 or earlier handled an object as MessagePack Array. It worked in Java world since the library was able to get field names using Java's reflection, but outside Java it was just an array of values and there was no way to get field names.

**Comment by cash2910** [comment]
> Yeah. How an object is serialized in MessagePack is different over MessagePack serialize/deserialize libraries.
> 
> Historically speaking, msgpack-java v6 or earlier handled an object as MessagePack Array. It worked in Java world since the library was able to get field names using Java's reflection, but outside Java it was just an array of values and there was no way to get field names.

I worked with PHP . and I got an array after serializing data from java.   I lose all the fields ...
but It worked at C# clients.

**Comment by komamitsu** [comment]
I'm closing this issue. If you still have any trouble with this issue, feel free to reopen it.
