### ISSUE TITLE
Nested serialization throws NullPointerException

### ISSUE THREAD

**Issue by hkalina** [msgpack/msgpack-java#508]
When serializing object whose getter use MessagePack serialization, the inner serialization breaks the outer serialization and it throws NullPointerException:
```
java.lang.NullPointerException
	at com.fasterxml.jackson.core.util.ByteArrayBuilder.write(ByteArrayBuilder.java:224)
	at org.msgpack.core.buffer.OutputStreamBufferOutput.write(OutputStreamBufferOutput.java:78)
	at org.msgpack.core.buffer.OutputStreamBufferOutput.writeBuffer(OutputStreamBufferOutput.java:71)
	at org.msgpack.core.MessagePacker.flushBuffer(MessagePacker.java:306)
	at org.msgpack.core.MessagePacker.flush(MessagePacker.java:281)
	at org.msgpack.core.MessagePacker.close(MessagePacker.java:296)
	at org.msgpack.jackson.dataformat.MessagePackGenerator.close(MessagePackGenerator.java:509)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3911)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3244)
	at org.msgpack.jackson.dataformat.MessagePackFactoryTest.testNestedSerialization(MessagePackFactoryTest.java:62)
```
It tries to write into ByteArrayBuilder which is already released/closed.

Reproducible using following test: (feel free to include this or derivated into msgpack tests)
```java
    @Test
    public void testNestedSerialization() throws Exception
    {
        ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
        objectMapper.writeValueAsBytes(new OuterClass());
    }

    public class OuterClass
    {
        public String getInner() throws JsonProcessingException
        {
            ObjectMapper m = new ObjectMapper(new MessagePackFactory());
            m.writeValueAsBytes(new InnerClass());
            return "EFG";
        }
    }

    public class InnerClass
    {
        public String getName()
        {
            return "ABC";
        }
    }
```
Identical test using standard (JSON) ObjectMapper works ok - only MessagePack is affected.

**Comment by zde** [comment]
FYI this is probably caused by storing the byte output buffer in a ThreadLocal in MessagePackGenerator. Should be either converted to a field, or properly saved/restored before use.

**Comment by komamitsu** [comment]
Wow, thanks for reporting that. I'll check it around mid-next week

**Comment by komamitsu** [comment]
I think we have 3 options:
1. Prevent a buffer in use from being used by another (nested) MessagePackGenerator by adding an internal flag that represents whether the buffer is still in use
    * This could generate garbage buffers in ThreadLocal whose flag says it's still used. To prevent those garbage buffers from remaining, a garbage collector is needed. I tried this idea in https://github.com/msgpack/msgpack-java/pull/509
2. `MessagePackFactory#setReuseResourceInGenerator(false)` prevents this issue. So changing the default value to `false` from `true` would address this issue
3. This issue won't happen in usual cases. So adding "`When serializing object whose getter use a nested MessagePack serialization, please call MessagePackFactory#setReuseResourceInGenerator(false)`" to README.md might be enough

I've observed 1 and 2 introduces performance degradations in different ways. I'm not sure we should  sacrifice performance for this kinda corner case. So I'll be choosing 3) as a workaround for now.
