### ISSUE TITLE
Cross serialization/deserialization PHP & Java

### ISSUE THREAD

**Issue by trK54Ylmz** [msgpack/msgpack-java#51]
I serialize array on PHP and putting data to database after Java takes data from database and deserializing the data. But I got error
- org.msgpack.MessageTypeException: Expected array, but got integer value

I think its encoding problem. There is no problem with PHP & Python serialize/deserialize process.

**Comment by vasumahesh1** [comment]
Hey,

I am trying to implement this , but without the couchbase Implementation .. but I am having problems encoding decoding cross platform .. whereas if i try to Decode/Encode within the same platform (Java & PHP) the conversions are working perfectly...

For eg:
in PHP i am compressing

`$data = array('id' => 1 , 'name' => 'yolo');`
using msgpack_pack();

and the output is:
`��id�name�yolo`

and on Java's Side if I compress it:
```
Temp src1 = new Temp();
src1.id = 1;
src1.name = "yolo";
MessagePack msgpack = new MessagePack();
byte[] bytes = msgpack.write(src1);
System.out.println(bytes);
```

the output is:
`[B@5c0369c4`

Shouldn't these two results be same for enabling cross conversions?

**Comment by vasumahesh1** [comment]
I have an update on the situation :

So Basically I tried to debug the Java End and found out that

```java
String re = readFile("msgpack-sample-2.txt");
tStart = System.currentTimeMillis();
byte[] bytesArray = Base64.getDecoder().decode(re);
ByteArrayInputStream bais = new ByteArrayInputStream(bytesArray);
Unpacker unpacker = msgpack.createUnpacker(bais);
Temp dst1 = unpacker.read(Temp.class);
```

so Temp class had `id,name`
so the Error was "Expected Array but was Map Value" because my PHP Array was :

```php
$data = array('id' => 4 , 'name' => 'yolo');
```
Indeed a Map Value.

and on the PHP's Side  if I change the `$data` to:

```php
$data = array(4 , 'yolo');
```

It works like a charm then. 

Now my question is how to make the Temp.class accept a MAP Value while unpacking? ...  say if i had 100 arguments it would be meaningless to append 100 values in one array and expecting them to be in the same order as in the Java Class Declaration. 

Please do reply!

Thanks
-Vasu

**Comment by komamitsu** [comment]
@vasumahesh1 Hm, your questions isn't related to this issue...

BTW, if you're using MessagePack v06, you need to write Template class like this:
```
    static class Temp {
        public int id;
        public String name;
    }

    static class TemplateForTemp extends AbstractTemplate<Temp> {
        @Override
        public void write(Packer packer, Temp temp, boolean b) throws IOException {
            packer.writeMapBegin(2);
            packer.write("id");
            packer.write(temp.id);
            packer.write("name");
            packer.write(temp.name);
            packer.flush();
        }

        @Override
        public Temp read(Unpacker values, Temp temp, boolean b) throws IOException {
            if (temp == null)
                temp = new Temp();

            int len = values.readMapBegin();
            for (int i = 0; i < len; i++) {
                String key = values.readString();
                if (key.equals("id")) {
                    temp.id = values.readInt();
                }
                else if (key.equals("name")) {
                    temp.name = values.readString();
                }
            }
            return temp;
        }
    }

    public void test() {
        byte[] bs = {...};
        MessagePack messagePack = new MessagePack();
        messagePack.register(Temp.class);

        Unpacker unpacker = messagePack.createUnpacker(new ByteArrayInputStream(bs));
        Temp t = unpacker.read(new TemplateForTemp());
    }
```

But you can convert it easier using jackson-dataformat-msgpack if you use MessagePack v07. https://github.com/msgpack/msgpack-java/tree/v07-develop/msgpack-jackson

```
        ObjectMapper objectMapper = new ObjectMapper(new MessagePackFactory());
        Temp temp = objectMapper.readValue(bs, Temp.class);
```

**Comment by vasumahesh1** [comment]
Hi,

Thanks for a reply...

But as I said above , if i have 100+ arguments I can't be doing something like

```java
String key = values.readString();
if (key.equals("id")) {
      temp.id = values.readInt();
}
else if (key.equals("name")) {
      temp.name = values.readString();
}
```
mapping 100 variables like this can be madness .... :/

**Comment by iraj-wisilica** [comment]
Any update on this issue? I am also struck on this.

**Comment by komamitsu** [comment]
Why don't you use msgpack-java v0.8? It can convert a MessagePack map value to POJO.
Also, unfortunately we no longer support msgpack v0.6.
