### ISSUE TITLE
Deserialize multiple objects (not in list)

### ISSUE THREAD

**Issue by chaykin** [msgpack/msgpack-java#517]
I have a stream with some POJO's. There is no info about objects count inside. And I need to deserealize it. This is code sample to do it:

```
TestPOJO pojo1 = new TestPOJO("test1");
TestPOJO pojo2 = new TestPOJO("test2");

ByteArrayOutputStream out = new ByteArrayOutputStream();
ObjectMapper mapper = new ObjectMapper(new MessagePackFactory());
mapper.configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false);

mapper.writeValue(out, pojo1);
mapper.writeValue(out, pojo2);
        

InputStream in = new ByteArrayInputStream(out.toByteArray());

mapper = new ObjectMapper(new MessagePackFactory());
mapper.configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false);

//mapper.readValue(in, TestPOJO.class);
//mapper.readValue(in, TestPOJO.class);

MappingIterator<TestPOJO> it = mapper.readValues(mapper.getFactory().createParser(in), TestPOJO.class);

it.readAll(); // throws exception
```

As a result of this code execution is exception:

```
com.fasterxml.jackson.core.io.JsonEOFException: Unexpected EOF
 at [Source: (ByteArrayInputStream); line: -1, column: 114]

	at org.msgpack.jackson.dataformat.MessagePackParser.nextToken(MessagePackParser.java:237)
	at com.fasterxml.jackson.databind.MappingIterator.hasNextValue(MappingIterator.java:240)
	at com.fasterxml.jackson.databind.MappingIterator.readAll(MappingIterator.java:316)
	at com.fasterxml.jackson.databind.MappingIterator.readAll(MappingIterator.java:303)
```

And, if I use #readValue method instead of #readValues, it works... but I don't know, how many POJO's in stream...

So, it seems, it is a bug

**Comment by NikitaZhelonkin** [comment]
I did it this way:
`  try {

            TestPOJO pojo1 = new TestPOJO("test1");
            TestPOJO pojo2 = new TestPOJO("test2");

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            MessagePackFactory factory = new MessagePackFactory();
            ObjectMapper mapper = new ObjectMapper(factory);
            mapper.configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false);

            mapper.writeValue(out, pojo1);
            mapper.writeValue(out, pojo2);


            InputStream in = new ByteArrayInputStream(out.toByteArray());

            mapper = new ObjectMapper(new MessagePackFactory());
            mapper.configure(JsonGenerator.Feature.AUTO_CLOSE_TARGET, false);

            JsonParser parser = factory.createParser(in);

            try{
                while (true){
                    mapper.readValue(parser, TestPOJO.class).toString();
                }
            }catch (Exception e){
                //do nothing
            }
        } catch (Exception e) {
            Log.e("TAG", e.toString());
        }
`

**Comment by chaykin** [comment]
Sorry, but I don't like this solution... What if we have real exception while execution? Say, stream is corrupted? We can lose some POSO's...

**Comment by komamitsu** [comment]
I guess @NikitaZhelonkin simplified the example code. How to handle an exception might depend on your use case.

This `jackson-dataformat-msgpack` is based on `jackson-databind` and I think this behaviour you reported can happen with `jackson-databind` as well. It would be better to ask the developers of the library.
