### ISSUE TITLE
Is this project dead? 

### ISSUE THREAD

**Issue by ramiws** [msgpack/msgpack-java#521]
Hi, 

This looks like a dead project to me because I wasted 3 hours navigating through dead links and not working/old examples:
1- check this:
MessagePack for Java
QuickStart for msgpack-java is available here. (https://github.com/msgpack/msgpack-java/wiki/QuickStart)  dead end 

2- the example on the main website showing oh how easy this is:
MessagePack msgpack = new MessagePack();
// Serialize
byte[] raw = msgpack.write(src);
Value dynamic = msgpack.read(raw);
List<String> dst2 = new Converter(dynamic)
    .read(Templates.tList(Templates.TString));

This example is so outdated that I checked all the way back to version 0.7.0-M1 and I did not find such calls as "msgpack.write(src)" and "msgpack.read(raw)". Can you imagine how outdated it is?

Please make this project useable or stop making new releases.

**Comment by xerial** [comment]
We had a big jump between version 6 and 7. I think you are looking at v6, which is no longer maintained.

**Comment by xerial** [comment]
> Is this project dead?
Absolutely no. Let me close the ticket.

**Comment by xerial** [comment]
@ramiws I see why you saw the obsolete doc. Thanks for reporting. I'll fix that doc.

**Comment by xerial** [comment]
The main site msgpack.org will be updated soon. The usage example can be found here https://github.com/msgpack/msgpack-java/blob/develop/msgpack-core/src/test/java/org/msgpack/core/example/MessagePackExample.java
