### ISSUE TITLE
use latest version of jackson (2.13.+)

### ISSUE THREAD

**Issue by pjfanning** [msgpack/msgpack-java#529]
Does cause 3 tests to fail:

https://github.com/msgpack/msgpack-java/runs/1048509743

**Comment by komamitsu** [comment]
Oh, interesting. Let me look into it later.

**Comment by hpx7** [comment]
I would love to use the [latest features](https://cowtowncoder.medium.com/jackson-2-12-features-eee9456fec75) in jackson 2.12 with this library if possible!

**Comment by komamitsu** [comment]
The latest version uses 2.13.
