### ISSUE TITLE
How to reduce the parsing time of Message pack library when unpacking large amount of data

### ISSUE THREAD

**Issue by KshitijGoMmt** [msgpack/msgpack-java#533]
For an android app, unpacking the data from streaming apis form the received InputStream, the parsing takes way too long. 

There is one single line of code that takes away around **600-800ms** for data of size **16.65kb.**

```
        ImmutableValue val = unpacker.unpackValue();
      **JSONObject jsonObj=new JOSNObject(val.toString());**
```

How can I make this faster? Its less than 50ms in iOS phone using MPMessagePack library which does the parsing in C language internally.

Here are the things I have already tried. 
 1. Tried the wrapper lib  https://github.com/msgpack/msgpack-java/blob/develop/msgpack-jackson/README.md that directly parses the data into models. Its equally slow.
 2.Tried to write my own parsing but that doesn't seem to speed up either. 
 3. Tried to traverse the whole ImmutableMapValue and putting key-values into JSONObject. That takes equal time as well.

Any idea how can we optimise this step?

**Comment by KshitijGoMmt** [comment]
@komamitsu Can you please shed some light on this. Something that probably not being done correctly by us, or any other way to speed it up. It would be great if we can reach anywhere close to the iOS benchmark.

**Comment by komamitsu** [comment]
```
        ImmutableValue val = unpacker.unpackValue();
```

The performance of parsing depends on source data and I didn't get what kind of data this `unpacker` contains. Could you give me reproducible code?

**Comment by KshitijGoMmt** [comment]
Thanks for the quick reply.
The line 
`ImmutableValue val = unpacker.unpackValue();`
works relatively quicker.

The issue is with this line majorly:

`**JSONObject jsonObj=new JOSNObject(val.toString());**`

And to be even more specific. Its with` **val.toString()**` method.

the val.toString() methods takes more than 600 ms for ~16kb of data. 


Let me ask if I can share the data since its private to the organisation I work for. If it's fine I will share in a while.

**Comment by KshitijGoMmt** [comment]
Please use this URL to check the conversion from ImmutableValue to String




curl --location --request GET 'https://thor.goibibo.com/v2/thor/rest/flight/search/mse/?userid=asd&hash=2837423032023&slotfl=y1&versioncode=720&actionData=%5B%7B%22query%22%3A%22air-DEL-BLR-20201124--1-0-0-E-100--%22%7D%5D&msgpack=true&mime=json&nearbyfl=y1&opf=1&application=fbs&flavour=ios' \
--header 'Cookie: _abck=735F0F1BDF3512BE636D9B6BD7B11542~-1~YAAQHa87F+0fHCtzAQAAfBRzTQSLaYoRgkLxEDmOlFIkCBtX9ikjuZjM2jx0m4hu3YfA/EfInaE44uN70lt9rH4ERpJbYid7iM0beNlvS932HeJorBPNsoGu/2xUDDj9Ci237p7Cvjhb6FLDUzbY4Jk227Np/lYyLQ2zX7wdS4hOwb7B9l521W3zhjmPnzhB+ELTw0lwu3upig9kXRZSmbcKPhtvAzenXn8l7iTLUSGPn2VPHmgLVtzOm7M4oKROwASA2bLQ9swIe71D4ntT1CPNZ2mgWYLsRPjq58eB+wTNEoJE8MGjH/lKqQ==~-1~-1~-1; ak_bmsc=8CC1F16D5D319BA3F46804BDE35C9927312C8D1CE306000010A6965FADD97D7F~ploAK2Qn4m+IodNUvDb6dgF69Ze2kHhlMtk0CkBDAx4EndKO7K4rOz/LqpVK7B3AmWrDZgPNIUsOFCrKUodFrIdhr5T5jKQVt7LFGk8SDu2BxRvplgJIjotiuULEgKYIWsqvv4zomcnLmNGX1ohzYJmWuUUr4bwf4iHFWCfLNgtDR9rl9XebZqHvixgy/0hSLMCaBSRkfuxwYX1GAzxkYlOiIATt7+2PDc2mvtd8tX71g=; bm_sz=79AD1D7A708CA8E38A665158149881AB~YAAQHI0sMVjIX1l1AQAA4q54ZAnbJKwVK5xkrbsjbtfSOLFOfZfCHbXTYoXbeC48ajDhpVWnBl126oxGRUiomPJo4LndvFDq3LDGOt8a6WV/22O7V4R0VfAKdQnIcYxdwhQNCmE93U6ybZSAFN2xmPKxzvwOs9ckt2BU3moqjPGtcNGB1GxVTWCT5pMCp0KQDw=='

**Comment by komamitsu** [comment]
I parsed the data with the following code and I couldn't reproduce the performance issue since it took only 60ms
```
        byte[] bytes = Files.readAllBytes(Paths.get("/Users/tmp/aaa/data"));
        long start;
        ImmutableValue value;
        {
            start = System.currentTimeMillis();
            MessageUnpacker unpacker = MessagePack.newDefaultUnpacker(bytes);
            value = unpacker.unpackValue();
            System.out.println(System.currentTimeMillis() - start);     >>> 60
        }
        {
            start = System.currentTimeMillis();
            String json = value.toString();
            System.out.println(System.currentTimeMillis() - start);     >>> 61
            System.out.println("The head of JSON data: " + json.substring(0, 12));    >>> "The head of JSON data: {"o":[{"id":"
            System.out.println("The length of JSON data: " + json.length());    >>> "The length of JSON data: 91807"
        }
```

BTW, `JOSNObject` isn't a part of msgpack-java and maybe you'd better ask the developer of the library about the performance of `JOSNObject`.

**Comment by KshitijGoMmt** [comment]
First of all what machine are you using to parse it?
1. Is it a desktop 
2. Or is it a mobile?

In my case I have been using this lib on Android mobile device and I suspect it could also be one possible reason for this mismatch in your timestamp logs and mine.

For these log I shared above, my code looked something like this:

               ```
               TimingLogger logger=new TimingLogger("UnpackTime","Start");

                String responseString = val.toString();
                logger.addSplit("ImmutableValue val to String");

                JSONObject object = new JSONObject(responseString);
                logger.addSplit(" String parsed to Platform JSON");

                logger.dumpToLog();
```

which results in this:
2020-10-26 15:08:39.934 29582-32399/com.xx.debug D/UnpackTime: Start:      762 ms, ImmutableValue val to String
2020-10-26 15:08:39.934 29582-32399/com.xx.debug D/UnpackTime: Start:      94 ms,  String parsed to platform JSON

So do you think on Android device could be a possible reason for this degradation in speed? 
Also can you tell me the machine's specs you used to parse this response?

**Comment by komamitsu** [comment]
Ah, msgpack-java uses `sun.misc.Unsafe` for performance optimization and the class isn't supported in Android . So msgpack-java in Android uses non performance optimized implementation. https://github.com/msgpack/msgpack-java/blob/bef0ccdb9b1be70c533f81e0c459fdef6f578cd2/msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBuffer.java#L87-L92
As you mentioned as question#1, I guess it may be related.

For 3, there are some options like https://stackoverflow.com/questions/1264709/convert-inputstream-to-byte-array-in-java

**Comment by KshitijGoMmt** [comment]
I tried the suggested link and it worked fine. The issue still was in the same thing, converting the value to String. i.e. val.toString();

I was doing some research on this class and android sdk classes. I found some interesting things.
 Here are my observations and questions based on them:

1.  Tried and copied the Unsafe.java class file from java platform but it doesn’t seem to recognise some imports

2.   I found in android sdk also there  is this Unsafe.java  class present under the sun.misc package, Could this be used as a replacement for this native java platform Unsafe class?
https://android.googlesource.com/platform/libcore/+/49965c1/ojluni/src/main/java/sun/misc/Unsafe.java
 If yes, for this also would I require to modify the lib code or can you provide us some way using configuration to set what class to be used for String parsing.

3.  Android has Kotlin as the official language now, does message-pack Kotlin provides this performance optimisation under the hood as Unsafe.java does in Java? 

4.  Is there any other workaround that you think would be the best way to achieve this same level of performance optimisation as you have get in Java?

Would you like to connect over a call to discuss it further or debug it together and find a working solution that is as good as native java?

**Comment by KshitijGoMmt** [comment]
@komamitsu Please let me know your thoughts on my suggestions. Looking forward to it.

**Comment by komamitsu** [comment]
> 1
msgpack-java detects the platform by checking some other other things not only the existence of Unsafe https://github.com/msgpack/msgpack-java/blob/bef0ccdb9b1be70c533f81e0c459fdef6f578cd2/msgpack-core/src/main/java/org/msgpack/core/buffer/MessageBuffer.java#L73-L92. I think you need to make `System.getProperty("java.runtime.name")` not to return `Android` at least. I'm not sure copying Unsafe works. though.

> 2
Java platforms can have different Unsafe implementations including different signatures. So it might work, but it might not work.

> 3
I'm not familiar with Kotlin implementation of MessagePack. But it might be worth trying.

> 4, 5
I have no idea for now...

**Comment by KshitijGoMmt** [comment]
@komamitsu  Sure I will give it a try and share the results if I find some workaround or any working solution.
Thanks for all of your help and quick responses. I totally appreciate it.
