### ISSUE TITLE
Indexed key annotation like in C# to optimize size

### ISSUE THREAD

**Issue by pilotpirxie** [msgpack/msgpack-java#543]
Hi, is it possible to annotate fields in class to auto-convert object to an array with indexes instead of key-value pairs?
Something like this (code in C#):
https://github.com/neuecc/MessagePack-CSharp#hints-to-achieve-maximum-performance-when-using-messagepack-for-c
```
[MessagePackObject]
public class Person
{
    [Key(0)] or [Key("name")]
    public string Name { get; set;}
    [Key(1)] or [Key("age")]
    public int Age { get; set;}
}

new Person { Name = "foobar", Age = 999 } 
```
which results in ["foobar", 9999]

From the message pack page:
```
{"compact":true,"schema":0}

MessagePack (hex) 18 bytes 67 %
```
but
```
[true, 0]

MessagePack (hex) 3 bytes 33 %
```

83% less in this example

**Comment by komamitsu** [comment]
You can use https://fasterxml.github.io/jackson-annotations/javadoc/2.8/com/fasterxml/jackson/annotation/JsonFormat.Shape.html like this

```
  @JsonFormat(shape=JsonFormat.Shape.ARRAY)
  public class Person
 {
    public String name;
    public int age;
        :
  }
```
