### ISSUE TITLE
MessagePackGenerator: Error handling BigDecimal 

### ISSUE THREAD

**Issue by deuveeme** [msgpack/msgpack-java#549]
Hi @komamitsu ,
I'm facing a "java.lang.IllegalArgumentException: MessagePack cannot serialize a BigDecimal that can't be represented as double. -8.773320999999999" but in my case it is due to the number is a periodic decimal (-8.77332099999999).  When it casts to a double it rounds the value and then when tries to compare with the initial value it realizes that it's not equal.
Have you faced this ever?

Many thanks for your time.

**Comment by komamitsu** [comment]
@deuveeme Can you give me a simple example code that reproduces this issue? I tried to reproduce this issue, but I couldn't...

**Comment by deuveeme** [comment]
@komamitsu 
sure. We faced the issue with a BigDecimal with the value -8.77332099999999.
I hope it helps you.

**Comment by komamitsu** [comment]
As I said, this issue hasn't been reproduced on my end like this
```
        ObjectMapper mapper = new ObjectMapper(new MessagePackFactory());

        HashMap<String, Object> map = new HashMap<>();
        map.put("k0", BigDecimal.valueOf(-8.77332099999999));
        map.put("k1", new BigDecimal("-8.77332099999999"));
        byte[] bytes = mapper.writeValueAsBytes(map);

        Map<String, Object> deserialized = mapper.readValue(bytes, new TypeReference<Map<String, Object>>() {});
        System.out.println(deserialized); /// >>> {k0=-8.77332099999999, k1=-8.77332099999999}
```

So I want to know how to reproduce this issue.

**Comment by deuveeme** [comment]
Hi and sorry for the delay.
The error raises from MessagePackGenerator.packBigDecimal(BigDecimal var).

**Comment by komamitsu** [comment]
@deuveeme I don't think you directly used the method. As I wrote above, I don't know how to reproduce this issue and I want you to give me a minimum code to reproduce it.

**Comment by deuveeme** [comment]
Hi @komamitsu, We have reproduced the error again. This time we faced the error serializing a number with 40 decimal figures. 
`ObjectMapper mapper = new ObjectMapper(new MessagePackFactory());
        HashMap<String, Object> map = new HashMap<>();
        map.put("k0", BigDecimal.valueOf(0.8398257518639524168551562369104465108486));
        map.put("k1", new BigDecimal("0.8398257518639524168551562369104465108486"));
        byte[] bytes = mapper.writeValueAsBytes(map);
        Map<String, Object> deserialized = mapper.readValue(bytes, new TypeReference<Object>() {});
        System.out.println(deserialized);`

**Comment by komamitsu** [comment]
@deuveeme Thanks for reproducing it!

Yes. MessagePack's float64 type is IEEE 754 64-bit double-precision, so the 40 decimal value can't be stored.

> float 64 stores a floating point number in IEEE 754 double precision floating point number format

https://github.com/msgpack/msgpack/blob/master/spec.md#float-format-family

If you want to avoid losing precision, I recommend to handle it as a string.

**Comment by komamitsu** [comment]
@deuveeme Found the solution https://github.com/msgpack/msgpack-java/pull/651/files
