### ISSUE TITLE
java.util.Locale register

### ISSUE THREAD

**Issue by VinayaP1** [msgpack/msgpack-java#672]
Hi, I'm using  msgpack version 0.6.12
I get this below error while registering Locale.  

org.msgpack.template.builder.TemplateBuildException: Cannot compile: 
{
  if (!$3 && $1.trySkipNil()) {
    return null;
  }
  java.util.Locale$LocaleNameGetter _$$_t;
  if ($2 == null) {
    _$$_t = new java.util.Locale$LocaleNameGetter();
  } else {
    _$$_t = (java.util.Locale$LocaleNameGetter) $2;
  }
  $1.readArrayBegin();
  $1.readArrayEnd();
  return _$$_t;
}

**Comment by komamitsu** [comment]
Sorry. The old version isn't supported now.
