### ISSUE TITLE
python模块的msgpack.packb方法在java怎么实现

### ISSUE THREAD

**Issue by wang-droid** [msgpack/msgpack-java#688]
>>> import msgpack
>>> msgpack.packb([1, 2, 3], use_bin_type=True)
'\x93\x01\x02\x03'

如上,看到python中有packb方法对数据进行打包序列化 这个操作用java怎么实现呢 有现成的方法吗

**Comment by komamitsu** [comment]
Sorry for the delayed response. I think you can use https://github.com/msgpack/msgpack-java/tree/develop/msgpack-jackson#serializationdeserialization-of-list as a reference.
