### ISSUE TITLE
java pack data is different from the data by other msg pack

### ISSUE THREAD

**Issue by oathleo** [msgpack/msgpack-java#73]
```
public class MyMessage {
    // public fields are serialized.
    public String name;
    public double version;
}
    MyMessage src = new MyMessage();
    src.name = "msgpack";
    src.version = 0.6;
```

bytes: [92 a7 6d 73 67 70 61 63 6b cb 3f e3 33 33 33 33 33 33  ]

but other msg pack like golang,
the byte:
[82 a4 6e 61 6d 65 a7 6d 73 67 70 61 63 6b a7 76 65 72 73 69 6f 6e cb 3f e3 33 33 33 33 33 33]

The java pack looks like missing the field's message.

**Comment by rasky** [comment]
Hello, we have the same problem; we need to serialize and deserialize msgpack data in a fixed format that we cannot control, and that format serializes objects as maps (not array). Would it be possible to add support for that?

**Comment by komamitsu** [comment]
@rasky Would this comment help you? https://github.com/msgpack/msgpack-java/issues/51#issuecomment-72041566
