### ISSUE TITLE
I don't know how can I get the Child , this is my code below, please help thank you very very much!!! 

### ISSUE THREAD

**Issue by Leeforrest** [msgpack/msgpack-java#74]
package com.dl;
import java.io.IOException;
import org.msgpack.MessagePack;
import org.msgpack.annotation.Message;
@Message
public class Test {
	public static void main(String[] args) {
		Parent p = new Child(2, 3);
		MessagePack pack = new MessagePack();
		pack.register(Parent.class);
		pack.register(Child.class);
		pack.register(Test.class);
		try {
			byte[] value = pack.write(p);
			Parent parent = pack.read(value, Parent.class);
			System.out.println(parent);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
@Message
class Parent{
	int a;
	public Parent() {
		
	}
	public Parent(int a) {
		this.a = a;
	}
	@Override
	public String toString() {
		
		return "a=" + this.a;
	}
}
@Message
class Child extends Parent{
	int b;
	public Child() {
		
	}
	public Child(int a, int b) {
		super(a);
		this.b = b;
	}
	@Override
	public String toString() {
		return "a=" + this.a + " b=" + this.b;
	}
}

The result is "a=2" which is not the one that I wanted,and
the result can be "a=2 b=3",if I change the param Parent.class to Child.class, but I wonder if the app can recoginse Child.class itsself by othe way ????Thank you very much

**Comment by komamitsu** [comment]
@Leeforrest Sorry for late reply. The caller of MessagePack needs to pass information to MessagePack about which class  the caller wants MessagePack to handle the serialized data as since MessagePack doesn't know it.

**Comment by komamitsu** [comment]
I'm closing this issue. Please re-open it if you still have any problem.
