### ISSUE TITLE
[Umbrella]Value support for v07

### ISSUE THREAD

**Issue by oza** [msgpack/msgpack-java#97]
This is an umbrella ticket for Value support for v07. I'll plan to change the class name as follows:

* ImmlutableValue -> Value
  * [feature] Creating Value instance for each objects
* MutableValue -> Cursor or Proxy 
  *  [feature] Creating Value instance at the initialization time, and reuse it.

**Comment by xerial** [comment]
Close this ticket and let us go with plan b) 
> b) let msgpack-core have both org.msgpack.core and org.msgpack.value packages.
